"use client";

import { useEffect, useRef, useState } from "react";
import { Bookmark, Check, ChevronLeft, ChevronRight, Download, Heart, Link2, MessageCircle, MoreHorizontal, Pencil, Play, Send, Trash2, Volume2, VolumeX, X } from "lucide-react";
import { formatCount, type Post } from "./data";

type FeedCardProps={post:Post;onToggleLike:(id:string)=>void;onToggleFollow:(id:string)=>void;onComment:(id:string,text:string)=>void;onEditComment:(postId:string,commentId:string,text:string)=>void;onDeleteComment:(postId:string,commentId:string)=>void;onShare:(id:string)=>void;onDelete:(id:string)=>void;onEdit:(id:string,caption:string)=>void;onToggleSave:(id:string)=>void;onDownload:(id:string,type:"image"|"video")=>void;onOpenVideo:(id:string)=>void;onLongPressVideo:(id:string)=>void};
export function FeedCard({post,onToggleLike,onToggleFollow,onComment,onEditComment,onDeleteComment,onShare,onDelete,onEdit,onToggleSave,onDownload,onOpenVideo,onLongPressVideo}:FeedCardProps){
 const [index,setIndex]=useState(0);const [showComments,setShowComments]=useState(false);const [commentText,setCommentText]=useState("");const [dragStartX,setDragStartX]=useState<number|null>(null);const [menuOpen,setMenuOpen]=useState(false);const [editing,setEditing]=useState(false);const [draft,setDraft]=useState(post.caption);const [commentMenu,setCommentMenu]=useState<string|null>(null);const [editingComment,setEditingComment]=useState<string|null>(null);const [commentDraft,setCommentDraft]=useState("");const [soundOn,setSoundOn]=useState(false);const pressTimerRef=useRef<ReturnType<typeof setTimeout>|null>(null);const longPressTriggeredRef=useRef(false);const movedRef=useRef(false);const videoRef=useRef<HTMLVideoElement|null>(null);const menuRef=useRef<HTMLDivElement|null>(null);const commentMenuRef=useRef<HTMLDivElement|null>(null);const total=post.media.length;
 useEffect(()=>{if(!menuOpen&&!commentMenu)return;const handler=(e:MouseEvent)=>{const t=e.target as Node;if(menuOpen&&menuRef.current&&!menuRef.current.contains(t))setMenuOpen(false);if(commentMenu&&commentMenuRef.current&&!commentMenuRef.current.contains(t))setCommentMenu(null);};document.addEventListener("mousedown",handler);return()=>document.removeEventListener("mousedown",handler);},[menuOpen,commentMenu]);
 useEffect(()=>{const video=videoRef.current;if(!video||!post.videoUrl)return;const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){video.muted=true;video.volume=0;setSoundOn(false);void video.play().catch(()=>undefined);}else video.pause();},{threshold:.6});observer.observe(video);return()=>observer.disconnect();},[post.videoUrl]);
 const goTo=(next:number)=>setIndex((next+total)%Math.max(total,1));
const cancelVideoPress=()=>{if(pressTimerRef.current){clearTimeout(pressTimerRef.current);pressTimerRef.current=null;}};
const handleVideoPointerDown=(e:React.PointerEvent<HTMLVideoElement>)=>{movedRef.current=false;longPressTriggeredRef.current=false;const startX=e.clientX,startY=e.clientY;cancelVideoPress();pressTimerRef.current=setTimeout(()=>{if(!movedRef.current){longPressTriggeredRef.current=true;onLongPressVideo(post.id);}},550);};
const handleVideoPointerUp=(e:React.PointerEvent<HTMLVideoElement>)=>{cancelVideoPress();if(!longPressTriggeredRef.current&&!movedRef.current){onOpenVideo(post.id);}longPressTriggeredRef.current=false;};
const handleVideoPointerMove=(e:React.PointerEvent<HTMLVideoElement>)=>{if(dragStartX!==null&&Math.abs(e.clientX-dragStartX)>12)movedRef.current=true;};
const handleVideoPointerCancel=()=>{cancelVideoPress();longPressTriggeredRef.current=false;movedRef.current=true;};
 const submitComment=()=>{const text=commentText.trim();if(!text)return;onComment(post.id,text);setCommentText("");};const saveEdit=()=>{const text=draft.trim();if(!text)return;onEdit(post.id,text);setEditing(false);};const startCommentEdit=(id:string,text:string)=>{setEditingComment(id);setCommentDraft(text);setCommentMenu(null);};const saveCommentEdit=(id:string)=>{const text=commentDraft.trim();if(!text)return;onEditComment(post.id,id,text);setEditingComment(null);setCommentDraft("");};
 const toggleVideoMute=async()=>{const video=videoRef.current;if(!video)return;if(video.muted||video.volume===0){video.muted=false;video.volume=1;setSoundOn(true);try{await video.play();}catch{video.muted=true;video.volume=0;setSoundOn(false);}}else{video.muted=true;video.volume=0;setSoundOn(false);}};
 const g1="#1476c9",g2="#35b6ff";
 return <article id={`post-${post.id}`} className="surface-card overflow-hidden border-[#153c68]" onContextMenu={e=>e.preventDefault()}>
  <div className="flex items-center gap-3 p-4"><span className="grid size-11 shrink-0 place-items-center rounded-full bg-[linear-gradient(140deg,#1476c9,#35b6ff)] text-xs font-black text-white">{post.author.initials}</span><div className="min-w-0 flex-1"><p className="truncate font-bold text-white">{post.author.name}</p><p className="text-xs text-[#7892ac]">{post.time}</p></div>{post.isOwn?<div className="relative" ref={menuRef}><button type="button" onClick={()=>setMenuOpen(o=>!o)} aria-label="Post options" className="icon-button"><MoreHorizontal size={20}/></button>{menuOpen?<div role="menu" className="absolute right-0 top-11 z-30 w-48 overflow-hidden rounded-2xl border border-[#18365f] bg-[#08182b] p-1.5 shadow-xl"><button type="button" onClick={()=>{setDraft(post.caption);setEditing(true);setMenuOpen(false);}} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold text-white hover:bg-[#0d2743]"><Pencil size={16}/>Edit text</button><button type="button" onClick={()=>{onDelete(post.id);setMenuOpen(false);}} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold text-[#ff8fa1] hover:bg-[#0d2743]"><Trash2 size={16}/>Delete post</button></div>:null}</div>:<button type="button" onClick={()=>onToggleFollow(post.author.id)} aria-pressed={post.following} className={`rounded-full px-4 py-1.5 text-xs font-bold ${post.following?"border border-[#285277] text-[#b7c9da]":"bg-[#167bd1] text-white"}`}>{post.following?"Following":"Follow"}</button>}</div>
  <div className="relative aspect-[4/3] w-full touch-pan-y select-none overflow-hidden bg-[#061120]" >{post.videoUrl?<><video ref={videoRef} src={post.videoUrl} poster={post.media[index]} muted playsInline loop autoPlay preload="metadata" className="absolute inset-0 size-full cursor-pointer object-cover" onPointerDown={handleVideoPointerDown} onPointerUp={handleVideoPointerUp} onPointerMove={handleVideoPointerMove} onPointerCancel={handleVideoPointerCancel} aria-label={`${post.author.name} video`}/><button type="button" onClick={toggleVideoMute} aria-label={soundOn?"Mute video":"Unmute video"} className="absolute bottom-3 right-3 z-10 grid size-10 place-items-center rounded-full border border-white/20 bg-black/55 text-white"><>{soundOn?<Volume2 size={18}/>:<VolumeX size={18}/>}</></button></>:post.media.map((src,i)=><img key={src+i} src={src||"/placeholder.svg"} alt={`${post.author.name} post media ${i+1}`} draggable={false} className="absolute inset-0 size-full object-cover transition-opacity duration-300" style={{opacity:i===index?1:0}}/>)}{total>1?<><span className="absolute right-3 top-3 rounded-full bg-black/55 px-2.5 py-1 text-[11px] font-bold text-white">{index+1}/{total}</span><button type="button" onClick={()=>goTo(index-1)} aria-label="Previous media" className="absolute left-2 top-1/2 grid size-8 -translate-y-1/2 place-items-center rounded-full bg-black/45 text-white"><ChevronLeft size={18}/></button><button type="button" onClick={()=>goTo(index+1)} aria-label="Next media" className="absolute right-2 top-1/2 grid size-8 -translate-y-1/2 place-items-center rounded-full bg-black/45 text-white"><ChevronRight size={18}/></button><div className="absolute bottom-3 left-1/2 flex -translate-x-1/2 gap-1.5">{post.media.map((src,i)=><button key={src+i} type="button" onClick={()=>setIndex(i)} aria-label={`Go to media ${i+1}`} className={`h-1.5 rounded-full ${i===index?"w-5 bg-white":"w-1.5 bg-white/50"}`}/>)}</div></>:null}</div>
  <div className="p-4">{editing?<div className="space-y-2"><textarea value={draft} onChange={e=>setDraft(e.target.value)} autoFocus rows={3} className="w-full resize-none rounded-2xl border border-[#18365f] bg-[#071426] p-3 text-sm text-white outline-none focus:border-[#2497ff]"/><div className="flex gap-2"><button type="button" onClick={saveEdit} className="flex items-center gap-1.5 rounded-full bg-[#167bd1] px-4 py-2 text-xs font-bold text-white"><Check size={15}/>Save</button><button type="button" onClick={()=>setEditing(false)} className="rounded-full border border-[#285277] px-4 py-2 text-xs font-bold text-[#b7c9da]">Cancel</button></div></div>:<p className="text-sm leading-6 text-[#d8e5f0]">{post.caption}</p>}
   <div className="mt-4 flex items-center gap-5 text-sm font-semibold"><button type="button" onClick={()=>onToggleLike(post.id)} aria-pressed={post.liked} className={`flex items-center gap-2 ${post.liked?"text-[#ff4d6d]":"text-[#b7c9da]"}`}><Heart size={20} fill={post.liked?"currentColor":"none"}/>{formatCount(post.likes)}</button><button type="button" onClick={()=>setShowComments(s=>!s)} aria-expanded={showComments} className="flex items-center gap-2 text-[#b7c9da]"><MessageCircle size={20}/>{formatCount(post.comments)}</button><button type="button" onClick={()=>onToggleSave(post.id)} aria-pressed={post.saved} className={`flex items-center gap-2 ${post.saved?"text-[#70c1ff]":"text-[#b7c9da]"}`}><Bookmark size={19} fill={post.saved?"currentColor":"none"}/>{post.saved?"Saved":"Save"}</button><button type="button" onClick={()=>onShare(post.id)} className="flex items-center gap-2 text-[#b7c9da]"><Link2 size={19}/>{formatCount(post.shares)}</button></div>
   {showComments?<div className="mt-4 border-t border-[#15304e] pt-4"><div className="mb-3 flex items-center justify-between"><p className="text-sm font-bold text-white">Comments</p><button type="button" onClick={()=>setShowComments(false)} aria-label="Close comments" className="grid size-7 place-items-center rounded-full text-[#7892ac]"><X size={16}/></button></div>{post.commentList.length?<ul className="space-y-3">{post.commentList.map(c=><li key={c.id} className="flex gap-2.5"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-[#0b3154] text-[10px] font-black text-[#70c1ff]">{c.author.split(" ").map(w=>w[0]).join("").slice(0,2).toUpperCase()}</span><div className="min-w-0 flex-1 rounded-2xl bg-[#0a1b2f] px-3 py-2"><div className="flex items-center gap-2"><p className="truncate text-xs font-bold text-white">{c.author}</p><span className="shrink-0 text-[10px] text-[#66809a]">{c.time}</span>{c.isOwn?<div className="relative ml-auto" ref={commentMenu===c.id?commentMenuRef:undefined}><button type="button" onClick={()=>setCommentMenu(x=>x===c.id?null:c.id)} aria-label="Comment options"><MoreHorizontal size={16}/></button>{commentMenu===c.id?<div role="menu" className="absolute right-0 top-7 z-40 w-32 rounded-xl border border-[#18365f] bg-[#08182b] p-1"><button type="button" onClick={()=>startCommentEdit(c.id,c.text)} className="flex w-full gap-2 rounded-lg px-2 py-2 text-xs text-white"><Pencil size={13}/>Edit</button><button type="button" onClick={()=>{onDeleteComment(post.id,c.id);setCommentMenu(null);}} className="flex w-full gap-2 rounded-lg px-2 py-2 text-xs text-[#ff8fa1]"><Trash2 size={13}/>Delete</button></div>:null}</div>:null}</div>{editingComment===c.id?<div className="mt-1.5 flex gap-2"><input value={commentDraft} onChange={e=>setCommentDraft(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")saveCommentEdit(c.id)}} className="min-w-0 flex-1 rounded-full border border-[#2497ff] bg-[#071426] px-3 py-1.5 text-sm text-white"/><button type="button" onClick={()=>saveCommentEdit(c.id)} className="grid size-8 place-items-center rounded-full bg-[#167bd1] text-white"><Check size={15}/></button></div>:<p className="mt-0.5 break-words text-sm text-[#d8e5f0]">{c.text}</p>}</div></li>)}</ul>:<p className="text-sm text-[#7892ac]">Be the first to comment.</p>}<div className="mt-3 flex items-center gap-2"><input value={commentText} onChange={e=>setCommentText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.nativeEvent.isComposing)e.keyCode!==229&&submitComment()}} placeholder="Add a comment..." className="flex-1 rounded-full border border-[#18365f] bg-[#071426] px-4 py-2 text-sm text-white outline-none"/><button type="button" onClick={submitComment} aria-label="Post comment" className="grid size-9 place-items-center rounded-full bg-[#167bd1] text-white"><Send size={16}/></button></div></div>:null}
  </div>
  {menuOpen&&!post.isOwn?<div className="fixed inset-0 z-[80] flex items-end justify-center bg-black/40 p-4 sm:items-center" onClick={()=>setMenuOpen(false)}><div className="w-full max-w-sm rounded-3xl border border-[#194b7c] bg-[#08182b] p-3" onClick={e=>e.stopPropagation()}><button type="button" onClick={()=>{onToggleSave(post.id);setMenuOpen(false)}} className="flex w-full items-center gap-3 rounded-2xl p-4 text-left text-sm font-bold text-white"><Bookmark size={18}/>{post.saved?"Unsave":"Save"}</button>{post.videoUrl?<button type="button" onClick={()=>{onDownload(post.id,"video");setMenuOpen(false)}} className="flex w-full items-center gap-3 rounded-2xl p-4 text-left text-sm font-bold text-white"><Download size={18}/>Download video</button>:post.media.length?<button type="button" onClick={()=>{onDownload(post.id,"image");setMenuOpen(false)}} className="flex w-full items-center gap-3 rounded-2xl p-4 text-left text-sm font-bold text-white"><Download size={18}/>Download image</button>:null}<button type="button" onClick={()=>setMenuOpen(false)} className="flex w-full items-center justify-center rounded-2xl border border-[#18365f] p-3 text-sm font-bold text-[#a9bdd5]">Cancel</button></div></div>:null}
 </article>;
}
