"use client";
import { useEffect, useRef, useState } from "react";
import { Bookmark, ChevronLeft, ChevronRight, Download, Forward, Heart, Link2, MessageCircle, MoreHorizontal, Pencil, Send, Trash2, UsersRound, Volume2, VolumeX, X } from "lucide-react";
import { formatCount, type Post } from "./data";
import { ContentForwarder } from "../share/content-forwarder";
import { PostTagger } from "../share/post-tagger";

type FeedCardProps={post:Post;onToggleLike:(id:string)=>void;onToggleFollow:(id:string)=>void;onComment:(id:string,text:string)=>void;onEditComment:(postId:string,commentId:string,text:string)=>void;onDeleteComment:(postId:string,commentId:string)=>void;onShare:(id:string)=>void;onDelete:(id:string)=>void;onEdit:(id:string,caption:string)=>void;onToggleSave:(id:string)=>void;onDownload:(id:string,type:"image"|"video")=>void;onOpenPost:(id:string)=>void;onOpenMedia:(id:string,index:number)=>void;onLongPressVideo?:(id:string)=>void};

export function FeedCard({post,onToggleLike,onToggleFollow,onComment,onEditComment,onDeleteComment,onShare,onDelete,onEdit,onToggleSave,onDownload,onOpenPost,onOpenMedia}:FeedCardProps){
 const [index,setIndex]=useState(0);const [showComments,setShowComments]=useState(false);const [commentText,setCommentText]=useState("");const [menuOpen,setMenuOpen]=useState(false);const [mediaMenuOpen,setMediaMenuOpen]=useState(false);const [forwardOpen,setForwardOpen]=useState(false);const [tagOpen,setTagOpen]=useState(false);const [editing,setEditing]=useState(false);const [draft,setDraft]=useState(post.caption);const [soundOn,setSoundOn]=useState(false);const pressTimerRef=useRef<ReturnType<typeof setTimeout>|null>(null);const pressStartRef=useRef<{x:number;y:number}|null>(null);const longPressTriggeredRef=useRef(false);const movedRef=useRef(false);const videoRef=useRef<HTMLVideoElement|null>(null);const menuRef=useRef<HTMLDivElement|null>(null);
 useEffect(()=>{if(!menuOpen)return;const handler=(e:MouseEvent)=>{const t=e.target as Node;if(menuRef.current&&!menuRef.current.contains(t))setMenuOpen(false)};document.addEventListener("mousedown",handler);return()=>document.removeEventListener("mousedown",handler)},[menuOpen]);
 useEffect(()=>{const video=videoRef.current;if(!video||!post.videoUrl)return;const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){video.muted=true;video.volume=0;setSoundOn(false);void video.play().catch(()=>undefined)}else video.pause()},{threshold:.6});observer.observe(video);return()=>observer.disconnect()},[post.videoUrl]);
 const cancelPress=()=>{if(pressTimerRef.current){clearTimeout(pressTimerRef.current);pressTimerRef.current=null}};
 const pointerDown=(e:React.PointerEvent<HTMLElement>)=>{movedRef.current=false;longPressTriggeredRef.current=false;pressStartRef.current={x:e.clientX,y:e.clientY};cancelPress();pressTimerRef.current=setTimeout(()=>{if(!movedRef.current){longPressTriggeredRef.current=true;setMediaMenuOpen(true);navigator.vibrate?.(12)}},600)};
 const pointerUp=(e:React.PointerEvent<HTMLElement>,mediaIndex:number)=>{cancelPress();if(!longPressTriggeredRef.current&&!movedRef.current)onOpenMedia(post.id,mediaIndex);pressStartRef.current=null;longPressTriggeredRef.current=false};
 const pointerMove=(e:React.PointerEvent<HTMLElement>)=>{const s=pressStartRef.current;if(s&&Math.hypot(e.clientX-s.x,e.clientY-s.y)>14){movedRef.current=true;cancelPress()}};const pointerCancel=()=>{cancelPress();movedRef.current=true;pressStartRef.current=null;longPressTriggeredRef.current=false};
 const submitComment=()=>{const text=commentText.trim();if(!text)return;onComment(post.id,text);setCommentText("")};const saveEdit=()=>{const text=draft.trim();if(!text)return;onEdit(post.id,text);setEditing(false)};const toggleVideoMute=async()=>{const video=videoRef.current;if(!video)return;if(video.muted||video.volume===0){video.muted=false;video.volume=1;setSoundOn(true);try{await video.play()}catch{video.muted=true;video.volume=0;setSoundOn(false)}}else{video.muted=true;video.volume=0;setSoundOn(false)}};const quickComments=post.commentList.slice(0,5);
 return <article id={`post-${post.id}`} className="surface-card overflow-hidden border-[#153c68]" onContextMenu={e=>e.preventDefault()}>
  <div className="flex items-center gap-3 p-4"><div className="grid size-11 shrink-0 place-items-center overflow-hidden rounded-full bg-[#0b3154] text-xs font-black text-white">{post.author.avatar?<img src={post.author.avatar} alt="" className="size-full object-cover"/>:post.author.initials}</div><div className="min-w-0 flex-1"><p className="truncate font-bold text-white">{post.author.name}</p><p className="text-xs text-[#7892ac]">{post.time}</p></div>{post.isOwn?<div className="relative" ref={menuRef}><button type="button" onClick={()=>setMenuOpen(o=>!o)} aria-label="Post options" className="icon-button"><MoreHorizontal size={20}/></button>{menuOpen?<div role="menu" className="absolute right-0 top-11 z-30 w-56 overflow-hidden rounded-2xl border border-[#18365f] bg-[#08182b] p-1.5 shadow-xl"><button type="button" onClick={()=>{setDraft(post.caption);setEditing(true);setMenuOpen(false)}} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold text-white"><Pencil size={16}/>Edit text</button><button type="button" onClick={()=>{setTagOpen(true);setMenuOpen(false)}} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold text-white"><UsersRound size={16}/>Tag people</button><button type="button" onClick={()=>{setForwardOpen(true);setMenuOpen(false)}} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold text-white"><Forward size={16}/>Forward post</button><button type="button" onClick={()=>{onDelete(post.id);setMenuOpen(false)}} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold text-[#ff9eaa]"><Trash2 size={16}/>Delete post</button></div>:null}</div>:<button type="button" onClick={e=>{e.stopPropagation();onToggleFollow(post.author.id)}} aria-pressed={post.following} className={`rounded-full px-4 py-1.5 text-xs font-bold ${post.following?"border border-[#285277] text-[#b7c9da]":"bg-[#167bd1] text-white"}`}>{post.following?"Unfollow":"Follow"}</button>}</div>
  {post.media.length?<div className="relative aspect-[4/3] w-full touch-pan-y select-none overflow-hidden bg-[#061120]" onClick={e=>e.stopPropagation()}>{post.videoUrl?<><video ref={videoRef} src={post.videoUrl} poster={post.media[index]} muted playsInline loop autoPlay preload="metadata" className="absolute inset-0 size-full cursor-pointer object-cover" onPointerDown={pointerDown} onPointerUp={e=>pointerUp(e,0)} onPointerMove={pointerMove} onPointerCancel={pointerCancel} aria-label={`${post.author.name} video`}/><button type="button" onClick={e=>{e.stopPropagation();void toggleVideoMute()}} aria-label={soundOn?"Mute video":"Unmute video"} className="absolute bottom-3 right-3 z-10 grid size-10 place-items-center rounded-full border border-white/20 bg-black/55 text-white">{soundOn?<Volume2 size={18}/>:<VolumeX size={18}/>}</button></>:post.media.map((src,i)=><img key={src+i} src={src||"/placeholder.svg"} alt={`${post.author.name} post media ${i+1}`} draggable={false} className="absolute inset-0 size-full cursor-pointer object-cover transition-opacity duration-300" style={{opacity:i===index?1:0}} onPointerDown={pointerDown} onPointerUp={e=>pointerUp(e,i)} onPointerMove={pointerMove} onPointerCancel={pointerCancel}/>)}{post.media.length>1?<><span className="absolute right-3 top-3 rounded-full bg-black/55 px-2.5 py-1 text-[11px] font-bold text-white">{index+1}/{post.media.length}</span><button type="button" onClick={e=>{e.stopPropagation();setIndex((index-1+post.media.length)%post.media.length)}} aria-label="Previous media" className="absolute left-2 top-1/2 grid size-8 -translate-y-1/2 items-center justify-center rounded-full bg-black/45 text-white"><ChevronLeft size={18}/></button><button type="button" onClick={e=>{e.stopPropagation();setIndex((index+1)%post.media.length)}} aria-label="Next media" className="absolute right-2 top-1/2 grid size-8 -translate-y-1/2 items-center justify-center rounded-full bg-black/45 text-white"><ChevronRight size={18}/></button></>:null}</div>:null}
  <div className="p-4" onClick={()=>onOpenPost(post.id)}>{editing?<div onClick={e=>e.stopPropagation()}><textarea value={draft} onChange={e=>setDraft(e.target.value)} rows={3} className="w-full rounded-2xl border border-[#18365f] bg-[#071426] p-3 text-sm text-white"/><button type="button" onClick={saveEdit} className="mt-2 rounded-full bg-[#167bd1] px-4 py-2 text-xs font-bold text-white">Save</button></div>:<p className="text-sm leading-6 text-[#d8e5f0]">{post.caption}</p>}
   <div className="mt-4 flex items-center gap-2 text-sm font-semibold" onClick={e=>e.stopPropagation()}><button type="button" onClick={()=>onToggleLike(post.id)} className={`flex items-center gap-2 rounded-full border px-3.5 py-2 ${post.liked?"border-[#2497ff] bg-[#0b3154] text-[#70c1ff]":"border-[#18365f] bg-[#071426] text-[#b7c9da]"}`}><Heart size={18} fill={post.liked?"currentColor":"none"}/>{formatCount(post.likes)}</button><button type="button" onClick={()=>setShowComments(true)} className="flex items-center gap-2 rounded-full border border-[#18365f] bg-[#071426] px-3.5 py-2 text-[#b7c9da]" aria-label="Open comments"><MessageCircle size={18}/>{formatCount(post.comments)}</button><button type="button" onClick={()=>onToggleSave(post.id)} className={`flex items-center gap-2 rounded-full border px-3.5 py-2 ${post.saved?"border-[#2497ff] bg-[#0b3154] text-[#70c1ff]":"border-[#18365f] bg-[#071426] text-[#b7c9da]"}`}><Bookmark size={18}/><span className="hidden sm:inline">{post.saved?"Saved":"Save"}</span></button><button type="button" onClick={()=>onShare(post.id)} aria-label="Share post link" className="flex items-center gap-2 rounded-full border border-[#18365f] bg-[#071426] px-3.5 py-2 text-[#b7c9da]"><Link2 size={18}/></button></div>
  </div>
  {mediaMenuOpen?<div className="fixed inset-0 z-[100] flex items-end justify-center bg-black/60 p-4 sm:items-center" onClick={()=>setMediaMenuOpen(false)}><div className="w-full max-w-sm rounded-3xl border border-[#194b7c] bg-[#08182b] p-3 shadow-2xl" onClick={e=>e.stopPropagation()}><p className="px-3 py-2 text-xs font-black uppercase tracking-[.14em] text-[#70c1ff]">Media actions</p><button type="button" onClick={()=>{onToggleSave(post.id);setMediaMenuOpen(false)}} className="flex w-full items-center gap-3 rounded-2xl p-4 text-left text-sm font-bold text-white"><Bookmark size={18}/>{post.saved?"Unsave":"Save"} {post.videoUrl?"Video":"Image"}</button><button type="button" onClick={()=>{onDownload(post.id,post.videoUrl?"video":"image");setMediaMenuOpen(false)}} className="flex w-full items-center gap-3 rounded-2xl p-4 text-left text-sm font-bold text-white"><Download size={18}/>Download {post.videoUrl?"Video":"Image"}</button><button type="button" onClick={()=>setMediaMenuOpen(false)} className="mt-1 flex w-full items-center justify-center rounded-2xl bg-[#0b3154] p-3 text-sm font-bold text-[#b7c9da]">Cancel</button></div></div>:null}
  {showComments?<div className="fixed inset-0 z-[110] flex items-end bg-black/55" role="dialog" aria-modal="true" onClick={()=>setShowComments(false)}><section className="max-h-[82vh] w-full overflow-hidden rounded-t-[28px] border border-[#194b7c] bg-[#071426] shadow-2xl" onClick={e=>e.stopPropagation()}><div className="mx-auto mt-3 h-1.5 w-12 rounded-full bg-[#36506b]"/><div className="flex items-center justify-between border-b border-[#153c68] px-5 py-4"><div><h2 className="text-lg font-black text-white">Comments</h2><p className="text-xs text-[#86a1bb]">{formatCount(post.comments)} comments</p></div><button type="button" onClick={()=>setShowComments(false)} aria-label="Close comments" className="icon-button"><X size={18}/></button></div><div className="max-h-[58vh] overflow-y-auto px-5 py-3">{quickComments.map(c=><div key={c.id} className="border-b border-[#15304e] py-4"><div className="flex gap-3"><div className="grid size-9 shrink-0 place-items-center rounded-full bg-[#0b3154] text-xs font-black text-[#70c1ff]">{c.author.slice(0,1).toUpperCase()}</div><div className="min-w-0 flex-1"><p className="text-sm font-black text-white">{c.author}</p><p className="mt-1 text-sm leading-5 text-[#d8e5f0]">{c.text}</p><div className="mt-2 flex items-center gap-4 text-[11px] font-bold text-[#7892ac]"><span>{c.time}</span><button type="button" className="text-[#70c1ff]">Reply</button></div></div></div></div>)}{!quickComments.length?<div className="py-12 text-center text-sm text-[#86a1bb]">No comments yet. Start the conversation.</div>:null}{post.comments>5?<button type="button" onClick={()=>onOpenPost(post.id)} className="my-3 text-sm font-black text-[#70c1ff]">View all {post.comments} comments</button>:null}</div><div className="border-t border-[#153c68] bg-[#071b2f] p-3 pb-[calc(.75rem+env(safe-area-inset-bottom))]"><div className="flex items-center gap-2 rounded-2xl border border-[#18365f] bg-[#0a2139] px-3 py-2"><input value={commentText} onChange={e=>setCommentText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")submitComment()}} placeholder="Add a comment..." aria-label="Add a comment" className="min-w-0 flex-1 bg-transparent px-1 py-2 text-sm text-white outline-none placeholder:text-[#7892ac]"/><button type="button" aria-label="Add emoji" className="grid size-9 shrink-0 place-items-center rounded-full text-xl">😊</button><button type="button" aria-label="Tag someone" className="grid size-9 shrink-0 place-items-center rounded-full text-lg font-black text-[#70c1ff]">@</button><button type="button" onClick={submitComment} aria-label="Send comment" className="grid size-9 shrink-0 place-items-center rounded-full bg-[#167bd1] text-white"><Send size={16}/></button></div></div></section></div>:null}
  <ContentForwarder open={forwardOpen} onClose={()=>setForwardOpen(false)} title={`Post by ${post.author.name}`} contentUrl={`${typeof window!=="undefined"?window.location.origin:""}/feeds/post/${post.id}`}/><PostTagger open={tagOpen} onClose={()=>setTagOpen(false)} postId={post.id}/>
 </article>;
}
