"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ChevronLeft, ChevronRight, Heart, MessageCircle, Reply } from "lucide-react";
import { useParams, useRouter, useSearchParams } from "next/navigation";
import { createBrowserSupabaseClient } from "../../lib/supabase/client";

type Media={storage_path:string;media_type:"image"|"video";position:number;url:string};
export function MediaViewer(){
 const params=useParams<{id:string}>();const query=useSearchParams();const router=useRouter();const supabase=useMemo(()=>createBrowserSupabaseClient(),[]);const [media,setMedia]=useState<Media[]>([]);const [index,setIndex]=useState(Number(query.get("index")||0));const [liked,setLiked]=useState(false);const [likes,setLikes]=useState(0);const [userId,setUserId]=useState("");const [loading,setLoading]=useState(true);
 useEffect(()=>{let alive=true;(async()=>{const [{data:auth},{data:ms},{data:ls}]=await Promise.all([supabase.auth.getUser(),supabase.from("post_media").select("storage_path,media_type,position").eq("post_id",params.id).order("position"),supabase.from("post_likes").select("user_id").eq("post_id",params.id)]);if(!alive)return;const uid=auth.user?.id||"";setUserId(uid);setMedia((ms||[]).map((m:any)=>({...m,url:supabase.storage.from("feed-media").getPublicUrl(m.storage_path).data.publicUrl})));setLikes((ls||[]).length);setLiked(Boolean(uid&&(ls||[]).some((l:any)=>l.user_id===uid)));setLoading(false);})();return()=>{alive=false};},[params.id,supabase]);
 const toggleLike=async()=>{if(!userId)return;if(liked){const {error}=await supabase.from("post_likes").delete().eq("post_id",params.id).eq("user_id",userId);if(!error){setLiked(false);setLikes(v=>Math.max(0,v-1));}}else{const {error}=await supabase.from("post_likes").insert({post_id:params.id,user_id:userId});if(!error){setLiked(true);setLikes(v=>v+1);}}};
 if(loading)return <main className="fixed inset-0 grid place-items-center bg-black text-white">Loading media…</main>;if(!media.length)return <main className="fixed inset-0 grid place-items-center bg-black text-white"><p>Media not found.</p></main>;
 const current=media[Math.max(0,Math.min(index,media.length-1))];
 return <main className="fixed inset-0 z-[100] flex flex-col bg-black text-white"><header className="flex items-center gap-3 border-b border-white/10 px-4 py-3"><button type="button" onClick={()=>router.back()} aria-label="Back" className="grid size-10 place-items-center rounded-full bg-white/10"><ArrowLeft size={19}/></button><p className="flex-1 text-sm font-black">{media.length>1?`${index+1} / ${media.length}`:"Media"}</p></header><div className="relative flex min-h-0 flex-1 items-center justify-center"><button type="button" onClick={()=>setIndex(v=>(v-1+media.length)%media.length)} aria-label="Previous media" className="absolute left-3 z-10 grid size-10 place-items-center rounded-full bg-white/10 disabled:opacity-30" disabled={media.length<2}><ChevronLeft size={22}/></button>{current.media_type==="video"?<video src={current.url} controls autoPlay playsInline className="max-h-full max-w-full object-contain"/>:<img src={current.url} alt="Post media" className="max-h-full max-w-full object-contain"/>}<button type="button" onClick={()=>setIndex(v=>(v+1)%media.length)} aria-label="Next media" className="absolute right-3 z-10 grid size-10 place-items-center rounded-full bg-white/10 disabled:opacity-30" disabled={media.length<2}><ChevronRight size={22}/></button></div><div className="flex items-center justify-center gap-8 border-t border-white/10 bg-black px-4 py-4"><button type="button" onClick={()=>void toggleLike()} disabled={!userId} className={`flex items-center gap-2 text-sm font-bold ${liked?"text-[#2497ff]":"text-white"}`}><Heart size={21} fill={liked?"currentColor":"none"}/>{likes}</button><button type="button" onClick={()=>router.push(`/feeds/post/${params.id}`)} className="flex items-center gap-2 text-sm font-bold text-white"><MessageCircle size={21}/>Comments</button><button type="button" onClick={()=>router.push(`/feeds/post/${params.id}#reply`)} className="flex items-center gap-2 text-sm font-bold text-[#70c1ff]"><Reply size={20}/>Reply</button></div></main>;
}
