"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Heart, MessageCircle, Reply, Send } from "lucide-react";
import { useRouter, useParams } from "next/navigation";
import { createBrowserSupabaseClient } from "../../lib/supabase/client";

type Comment={id:string;body:string;created_at:string;author_id:string;name:string};
type Media={storage_path:string;media_type:"image"|"video";position:number;url:string};

export function PostDetail(){
 const params=useParams<{id:string}>();const router=useRouter();const supabase=useMemo(()=>createBrowserSupabaseClient(),[]);const [post,setPost]=useState<any>(null);const [media,setMedia]=useState<Media[]>([]);const [comments,setComments]=useState<Comment[]>([]);const [userId,setUserId]=useState("");const [liked,setLiked]=useState(false);const [likeCount,setLikeCount]=useState(0);const [text,setText]=useState("");const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 useEffect(()=>{let alive=true;(async()=>{const [{data:auth},{data:p,error:pe}]=await Promise.all([supabase.auth.getUser(),supabase.from("posts").select("id,author_id,body,media_kind,created_at,profiles:author_id(display_name,username,avatar_path)").eq("id",params.id).maybeSingle()]);if(!alive)return;const uid=auth.user?.id||"";setUserId(uid);if(pe||!p){setError(pe?.message||"Post not found");setLoading(false);return;}setPost(p);const [{data:ms},{data:cs},{data:ls}]=await Promise.all([supabase.from("post_media").select("storage_path,media_type,position").eq("post_id",params.id).order("position"),supabase.from("post_comments").select("id,body,created_at,author_id,profiles:author_id(display_name,username)").eq("post_id",params.id).order("created_at",{ascending:true}),supabase.from("post_likes").select("user_id").eq("post_id",params.id)]);setMedia((ms||[]).map((m:any)=>({...m,url:supabase.storage.from("feed-media").getPublicUrl(m.storage_path).data.publicUrl})));setComments((cs||[]).map((c:any)=>({id:c.id,body:c.body,created_at:c.created_at,author_id:c.author_id,name:c.profiles?.display_name||c.profiles?.username||"MatchUp Player"})));setLikeCount((ls||[]).length);setLiked(Boolean(uid&&(ls||[]).some((l:any)=>l.user_id===uid)));setLoading(false);})();return()=>{alive=false};},[params.id,supabase]);
 const toggleLike=async()=>{if(!userId)return;if(liked){const {error:e}=await supabase.from("post_likes").delete().eq("post_id",params.id).eq("user_id",userId);if(!e){setLiked(false);setLikeCount(v=>Math.max(0,v-1));}}else{const {error:e}=await supabase.from("post_likes").insert({post_id:params.id,user_id:userId});if(!e){setLiked(true);setLikeCount(v=>v+1);}}};
 const addComment=async()=>{const body=text.trim();if(!body||!userId)return;const {data,error:e}=await supabase.from("post_comments").insert({post_id:params.id,author_id:userId,body}).select("id,body,created_at,author_id").single();if(e){setError(e.message);return;}setComments(v=>[...v,{...(data as any),name:"You"}]);setText("");};
 if(loading)return <main className="min-h-screen bg-[#061120] p-4 text-white"><p>Loading post…</p></main>;if(error||!post)return <main className="min-h-screen bg-[#061120] p-4 text-white"><button type="button" onClick={()=>router.back()} className="mb-5 grid size-10 place-items-center rounded-full bg-[#0b3154]"><ArrowLeft size={19}/></button><p>{error||"Post not found"}</p></main>;
 const name=post.profiles?.display_name||post.profiles?.username||"MatchUp Player";
 return <main className="min-h-screen bg-[#061120] pb-8 text-white"><header className="sticky top-0 z-20 flex items-center gap-3 border-b border-[#18365f] bg-[#061120]/95 px-4 py-3 backdrop-blur"><button type="button" onClick={()=>router.back()} aria-label="Back" className="grid size-10 place-items-center rounded-full bg-[#0b3154]"><ArrowLeft size={19}/></button><div className="min-w-0"><p className="truncate font-black">{name}</p><p className="text-[11px] text-[#7892ac]">Post detail</p></div></header><article className="mx-auto max-w-2xl"><div className="px-4 py-5"><p className="text-base leading-7 text-[#d8e5f0]">{post.body}</p></div>{media.map(m=>m.media_type==="video"?<video key={m.storage_path} src={m.url} controls playsInline className="max-h-[75vh] w-full bg-black object-contain"/>:<img key={m.storage_path} src={m.url} alt="Post media" className="max-h-[75vh] w-full bg-black object-contain"/>) }<div className="flex items-center gap-5 border-b border-[#18365f] px-4 py-4"><button type="button" onClick={()=>void toggleLike()} disabled={!userId} className={`flex items-center gap-2 text-sm font-bold ${liked?"text-[#2497ff]":"text-[#b7c9da]"}`}><Heart size={21} fill={liked?"currentColor":"none"}/>{likeCount}</button><span className="flex items-center gap-2 text-sm font-bold text-[#b7c9da]"><MessageCircle size={20}/>{comments.length}</span><button type="button" onClick={()=>document.getElementById("reply")?.focus()} className="ml-auto flex items-center gap-2 text-sm font-bold text-[#70c1ff]"><Reply size={19}/>Reply</button></div><section className="px-4 py-5"><h2 className="text-lg font-black">Comments</h2><div className="mt-4 space-y-3">{comments.length?comments.map(c=><div key={c.id} className="rounded-2xl border border-[#18365f] bg-[#071426] p-3"><p className="text-xs font-black text-[#70c1ff]">{c.name}</p><p className="mt-1 text-sm leading-6 text-[#d8e5f0]">{c.body}</p></div>):<p className="text-sm text-[#7892ac]">No comments yet.</p>}</div><div className="sticky bottom-0 mt-5 flex gap-2 border-t border-[#18365f] bg-[#061120] py-3"><input id="reply" value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void addComment()}} disabled={!userId} placeholder={userId?"Write a reply…":"Sign in to reply"} className="min-w-0 flex-1 rounded-full border border-[#214a78] bg-[#071426] px-4 py-3 text-sm outline-none focus:border-[#2497ff]"/><button type="button" onClick={()=>void addComment()} disabled={!userId||!text.trim()} aria-label="Send reply" className="grid size-11 shrink-0 place-items-center rounded-full bg-[#167bd1] disabled:opacity-40"><Send size={17}/></button></div></section></article></main>;
}
