"use client";
import { useCallback,useEffect,useMemo,useRef,useState } from "react";
import { ArrowLeft, Heart, MessageCircle, Send, Volume2, VolumeX, X } from "lucide-react";
import { useRouter,useSearchParams } from "next/navigation";
import { createBrowserSupabaseClient } from "../../lib/supabase/client";
type Reel={id:string;authorId:string;author:string;body:string;videoUrl:string;likes:number;liked:boolean;comments:{id:string;author:string;body:string}[]};
export function ReelsViewer(){
  const router=useRouter();const params=useSearchParams();const supabase=useMemo(()=>createBrowserSupabaseClient(),[]);const selectedId=params.get("post")||"";const originTab=params.get("tab")==="following"?"following":"for-you";const originQuery=params.get("q")||"";const originScroll=params.get("scroll")||"0";const [reels,setReels]=useState<Reel[]>([]);const [active,setActive]=useState(0);const [userId,setUserId]=useState("");const [commentsOpen,setCommentsOpen]=useState(false);const [commentText,setCommentText]=useState("");const [muted,setMuted]=useState(true);const videoRefs=useRef<Record<string,HTMLVideoElement|null>>({});
  const feedUrl=`/feeds?tab=${encodeURIComponent(originTab)}&q=${encodeURIComponent(originQuery)}&post=${encodeURIComponent(selectedId)}&scroll=${encodeURIComponent(originScroll)}`;const leave=useCallback(()=>{setCommentsOpen(false);router.replace(feedUrl);},[router,feedUrl]);
  useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(e.key!=="Escape"&&e.key!=="Backspace")return;if((e.target as HTMLElement)?.tagName==="INPUT"||(e.target as HTMLElement)?.tagName==="TEXTAREA")return;if(commentsOpen){setCommentsOpen(false);return;}if(e.key==="Escape")leave();};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey);},[commentsOpen,leave]);
  useEffect(()=>{const onPopState=()=>{if(!commentsOpen)return;window.history.pushState(null,"",window.location.href);setCommentsOpen(false);};if(commentsOpen)window.history.pushState(null,"",window.location.href);window.addEventListener("popstate",onPopState);return()=>window.removeEventListener("popstate",onPopState);},[commentsOpen]);
  useEffect(()=>{let alive=true;(async()=>{const {data:auth}=await supabase.auth.getUser();const uid=auth.user?.id||"";if(alive)setUserId(uid);const {data:rows}=await supabase.from("posts").select("id,author_id,body,created_at").eq("media_kind","video").order("created_at",{ascending:false}).limit(100);if(!alive)return;const {data:followRows}=uid?await supabase.from("user_follows").select("following_id").eq("follower_id",uid):{data:[]};const followingIds=new Set((followRows||[]).map((f:any)=>f.following_id));const ids=(rows||[]).map((r:any)=>r.id);if(!ids.length){setReels([]);return;}const {data:media}=await supabase.from("post_media").select("post_id,storage_path,media_type").in("post_id",ids).eq("media_type","video");const {data:likes}=await supabase.from("post_likes").select("post_id,user_id").in("post_id",ids);const {data:comments}=await supabase.from("post_comments").select("id,post_id,author_id,body").in("post_id",ids).order("created_at",{ascending:true});const authorIds=Array.from(new Set([...(rows||[]).map((r:any)=>r.author_id),...(comments||[]).map((c:any)=>c.author_id)]));const {data:profiles}=await supabase.from("profiles").select("id,display_name,username").in("id",authorIds);const pmap=new Map((profiles||[]).map((p:any)=>[p.id,p]));const cmap=new Map<string,any[]>();(comments||[]).forEach((c:any)=>{const a=pmap.get(c.author_id);const list=cmap.get(c.post_id)||[];list.push({id:c.id,author:a?.display_name||a?.username||"MatchUp Player",body:c.body});cmap.set(c.post_id,list);});const built=(rows||[]).map((r:any)=>{const m=(media||[]).find((x:any)=>x.post_id===r.id);if(!m)return null;const {data:url}=supabase.storage.from("feed-media").getPublicUrl(m.storage_path);const a=pmap.get(r.author_id);return {id:r.id,authorId:r.author_id,author:a?.display_name||a?.username||"MatchUp Player",body:r.body,videoUrl:url.publicUrl,likes:(likes||[]).filter((l:any)=>l.post_id===r.id).length,liked:uid?Boolean((likes||[]).find((l:any)=>l.post_id===r.id&&l.user_id===uid)):false,comments:cmap.get(r.id)||[]};}).filter(Boolean) as Reel[];const eligible=originTab==="following"&&uid?built.filter(r=>followingIds.has(r.authorId)||r.authorId===uid):built;setReels(eligible);const selectedIndex=eligible.findIndex(r=>r.id===selectedId);setActive(selectedIndex>=0?selectedIndex:0);})();return()=>{alive=false;};},[supabase,selectedId,originTab]);
  useEffect(()=>{reels.forEach((r,i)=>{const v=videoRefs.current[r.id];if(!v)return;if(i===active){v.muted=muted;void v.play().catch(()=>{});}else{v.pause();v.currentTime=0;}});},[active,reels,muted]);
  const toggleLike=async()=>{const r=reels[active];if(!r||!userId)return;const result=r.liked?await supabase.from("post_likes").delete().eq("post_id",r.id).eq("user_id",userId):await supabase.from("post_likes").insert({post_id:r.id,user_id:userId});if(!result.error)setReels(x=>x.map((a,i)=>i===active?{...a,liked:!a.liked,likes:a.likes+(a.liked?-1:1)}:a));};
  const addComment=async()=>{const text=commentText.trim();const r=reels[active];if(!text||!r||!userId)return;const {data,error}=await supabase.from("post_comments").insert({post_id:r.id,author_id:userId,body:text}).select("id,body").single();if(!error&&data){setReels(x=>x.map((a,i)=>i===active?{...a,comments:[...a.comments,{id:data.id,author:"You",body:data.body}]}:a));setCommentText("");}};
  if(!reels.length)return <main className="fixed inset-0 grid place-items-center bg-black text-white"><div className="text-center"><div className="mx-auto mb-3 size-9 animate-spin rounded-full border-2 border-white/20 border-t-white"/><p className="text-sm text-white/70">Loading Reels…</p></div></main>;
  const current=reels[active];
  return <main className="fixed inset-0 z-[100] bg-black text-white">
    <div className="pointer-events-none absolute inset-x-0 top-0 z-30 h-28 bg-gradient-to-b from-black/75 to-transparent"/>
    <div className="absolute inset-x-0 top-0 z-40 flex items-center justify-between p-4 sm:p-5">
      <button type="button" onClick={commentsOpen?()=>setCommentsOpen(false):leave} aria-label={commentsOpen?"Close comments":"Back to feed"} className="grid size-10 place-items-center rounded-full border border-white/10 bg-black/45 text-white backdrop-blur-md transition hover:bg-black/65">{commentsOpen?<X size={21}/>:<ArrowLeft size={21}/>}</button>
      <div className="text-center"><span className="text-base font-black tracking-tight">Reels</span><span className="ml-2 text-xs font-semibold text-white/55">{active+1} / {reels.length}</span></div>
      <button type="button" onClick={()=>setMuted(x=>!x)} aria-label={muted?"Turn sound on":"Mute"} className="grid size-10 place-items-center rounded-full border border-white/10 bg-black/45 text-white backdrop-blur-md transition hover:bg-black/65">{muted?<VolumeX size={19}/>:<Volume2 size={19}/>}</button>
    </div>
    <div className="h-full snap-y snap-mandatory overflow-y-auto overscroll-contain scrollbar-none" onScroll={e=>{const el=e.currentTarget;const i=Math.round(el.scrollTop/el.clientHeight);if(i!==active)setActive(Math.max(0,Math.min(i,reels.length-1)));}}>
      {reels.map((r,i)=><section key={r.id} className="relative flex h-full min-h-full snap-start items-center justify-center bg-black">
        <video ref={v=>{videoRefs.current[r.id]=v}} src={r.videoUrl} playsInline loop muted={muted} preload={i===active?"auto":"metadata"} className="h-full w-full object-contain" aria-label={`${r.author} video`}/>
        <div className="pointer-events-none absolute inset-x-0 bottom-0 h-64 bg-gradient-to-t from-black/90 via-black/35 to-transparent"/>
        <div className="absolute inset-x-0 bottom-0 z-20 flex items-end justify-between gap-4 p-5 pb-8 sm:p-8 sm:pb-10">
          <div className="min-w-0 max-w-[min(620px,calc(100%-88px))]">
            <div className="mb-2 flex items-center gap-2"><span className="grid size-9 place-items-center rounded-full bg-white/15 text-[10px] font-black ring-1 ring-white/20">{r.author.split(" ").map(w=>w[0]).join("").slice(0,2).toUpperCase()}</span><p className="truncate text-sm font-black text-white">{r.author}</p></div>
            {r.body?<p className="line-clamp-3 text-sm leading-5 text-white/90 sm:text-base">{r.body}</p>:null}
          </div>
          <div className="flex shrink-0 flex-col items-center gap-5 pb-1">
            <button type="button" onClick={toggleLike} aria-label={r.liked?"Unlike video":"Like video"} className="flex flex-col items-center gap-1.5 text-white"><span className={`grid size-12 place-items-center rounded-full border border-white/10 bg-black/45 backdrop-blur-md transition ${r.liked?"text-[#ff4d6d]":""}`}><Heart size={22} fill={r.liked?"currentColor":"none"}/></span><span className="text-[11px] font-bold">{r.likes}</span></button>
            <button type="button" onClick={()=>setCommentsOpen(true)} aria-label="Open comments" className="flex flex-col items-center gap-1.5 text-white"><span className="grid size-12 place-items-center rounded-full border border-white/10 bg-black/45 backdrop-blur-md"><MessageCircle size={22}/></span><span className="text-[11px] font-bold">{r.comments.length}</span></button>
          </div>
        </div>
      </section>)}
    </div>
    {commentsOpen?<div className="absolute inset-x-0 bottom-0 z-50 max-h-[70vh] rounded-t-[28px] border-t border-white/10 bg-[#08182b]/98 p-4 shadow-2xl backdrop-blur-xl sm:mx-auto sm:max-w-xl">
      <div className="mx-auto mb-3 h-1 w-10 rounded-full bg-white/20 sm:hidden"/>
      <div className="mb-3 flex items-center justify-between"><div><h2 className="font-black">Comments</h2><p className="text-xs text-white/45">{current?.author}</p></div><button type="button" onClick={()=>setCommentsOpen(false)} aria-label="Close comments" className="grid size-9 place-items-center rounded-full bg-white/5"><X size={19}/></button></div>
      <div className="max-h-[45vh] space-y-3 overflow-y-auto pr-1">{current?.comments.length?current.comments.map(c=><div key={c.id} className="rounded-2xl bg-white/[.06] p-3"><p className="text-xs font-bold">{c.author}</p><p className="mt-1 text-sm text-white/85">{c.body}</p></div>):<p className="py-6 text-center text-sm text-white/50">No comments yet.</p>}</div>
      <div className="mt-3 flex gap-2"><input value={commentText} onChange={e=>setCommentText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void addComment()}} placeholder={userId?"Add a comment…":"Sign in to comment"} disabled={!userId} className="min-w-0 flex-1 rounded-full border border-white/10 bg-black/25 px-4 py-3 text-sm outline-none focus:border-white/25"/><button type="button" onClick={()=>void addComment()} disabled={!userId} className="grid size-11 shrink-0 place-items-center rounded-full bg-[#d79a32] text-white disabled:opacity-40"><Send size={17}/></button></div>
    </div>:null}
  </main>;
}
