"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, Check, Clock3, Swords, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { createBrowserSupabaseClient } from "../../lib/supabase/client";
import { MatchUpAvatar } from "../ui/matchup-avatar";

type Profile={id:string;display_name:string|null;username:string|null;avatar_path:string|null;ready_player_enabled?:boolean};
type Request={id:string;requester_id:string;opponent_id:string;status:string;created_at:string;profile?:Profile};
const nameOf=(p:Profile)=>p.display_name||p.username||"MatchUp Player";
export function ReadyPlayersPage(){
 const router=useRouter(); const supabase=useMemo(()=>createBrowserSupabaseClient(),[]); const [me,setMe]=useState<Profile|null>(null); const [players,setPlayers]=useState<Profile[]>([]); const [incoming,setIncoming]=useState<Request[]>([]); const [outgoing,setOutgoing]=useState<Request[]>([]); const [busy,setBusy]=useState(""); const [loading,setLoading]=useState(true); const [notice,setNotice]=useState("");
 const load=useCallback(async()=>{const {data:a}=await supabase.auth.getUser();if(!a.user){router.push("/auth/sign-in");return}const id=a.user.id;const [{data:m},{data:ready},{data:inc},{data:out}]=await Promise.all([supabase.from("profiles").select("id,display_name,username,avatar_path,ready_player_enabled").eq("id",id).maybeSingle(),supabase.from("profiles").select("id,display_name,username,avatar_path,ready_player_enabled").eq("ready_player_enabled",true).neq("id",id).order("ready_player_updated_at",{ascending:false}),supabase.from("match_requests").select("id,requester_id,opponent_id,status,created_at").eq("opponent_id",id).eq("status","pending").order("created_at",{ascending:false}),supabase.from("match_requests").select("id,requester_id,opponent_id,status,created_at").eq("requester_id",id).eq("status","pending").order("created_at",{ascending:false})]);setMe(m as Profile|null);setPlayers((ready||[]) as Profile[]);const ids=[...(inc||[]).map((r:any)=>r.requester_id),...(out||[]).map((r:any)=>r.opponent_id)];const ps=ids.length?(await supabase.from("profiles").select("id,display_name,username,avatar_path,ready_player_enabled").in("id",Array.from(new Set(ids)))).data||[]:[];const map=new Map((ps as Profile[]).map(p=>[p.id,p]));setIncoming((inc||[]).map((r:any)=>({...r,profile:map.get(r.requester_id)})));setOutgoing((out||[]).map((r:any)=>({...r,profile:map.get(r.opponent_id)})));setLoading(false)},[router,supabase]);
 useEffect(()=>{void load();const ch=supabase.channel("ready-matchup").on("postgres_changes",{event:"*",schema:"public",table:"profiles"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"match_requests"},()=>void load()).subscribe();return()=>{void supabase.removeChannel(ch)}},[load,supabase]);
 const toggle=async()=>{if(!me)return;setBusy("ready");const {error}=await supabase.rpc("set_ready_player",{p_enabled:!me.ready_player_enabled});if(error)setNotice(error.message);else setNotice(!me.ready_player_enabled?"You are now marked ready to play.":"Ready Player is off.");await load();setBusy("")};
 const challenge=async(p:Profile)=>{setBusy(p.id);setNotice("");const {error}=await supabase.rpc("send_match_request",{p_opponent_id:p.id});if(error)setNotice(error.message);else setNotice(`Match request sent to ${nameOf(p)}.`);await load();setBusy("")};
 const respond=async(r:Request,accept:boolean)=>{setBusy(r.id);const {data,error}=await supabase.rpc("respond_match_request",{p_request_id:r.id,p_accept:accept});if(error)setNotice(error.message);else if(accept){const conv=(await supabase.from("match_conversations").select("conversation_id").eq("match_id",data).maybeSingle()).data?.conversation_id;if(conv)router.push(`/leaderboard?group=${conv}&match=${data}`);else setNotice("Match accepted")}else setNotice("Match request declined.");await load();setBusy("")};
 return <main className="min-h-screen bg-[#061120] px-4 pb-28 pt-5 text-white sm:px-6"><div className="mx-auto max-w-2xl"><header className="flex items-center gap-3 border-b border-white/5 pb-5"><button className="icon-button" onClick={()=>router.back()} aria-label="Back"><ArrowLeft size={18}/></button><div className="flex-1"><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#47a8ff]">Quick Match</p><h1 className="text-2xl font-black">Ready Players</h1></div><button disabled={busy==="ready"} onClick={()=>void toggle()} className={`rounded-2xl px-4 py-2.5 text-xs font-black ${me?.ready_player_enabled?"bg-[#35c58a] text-[#04150f]":"bg-[#167bd1] text-white"}`}>{me?.ready_player_enabled?"Ready":"Mark Ready"}</button></header>
 {notice?<div role="status" className="mt-4 rounded-2xl border border-[#205d8e] bg-[#0a2946] px-4 py-3 text-sm font-bold text-[#bfe3ff]">{notice}</div>:null}
 {incoming.length?<section className="mt-6"><h2 className="mb-3 text-sm font-black uppercase tracking-[.14em] text-[#70c1ff]">Match requests</h2><div className="space-y-2">{incoming.map(r=><div key={r.id} className="rounded-2xl border border-[#245b91] bg-[#071a2e] p-3"><div className="flex items-center gap-3"><MatchUpAvatar profile={r.profile} size="md" alt={r.profile?nameOf(r.profile):"Match request"}/><div className="min-w-0 flex-1"><p className="font-black">{r.profile?nameOf(r.profile):"MatchUp Player"}</p><p className="text-xs text-[#7892ac]">wants to play a quick 1v1 match</p></div><Clock3 size={16} className="text-[#70c1ff]"/></div><div className="mt-3 grid grid-cols-2 gap-2"><button disabled={busy===r.id} onClick={()=>void respond(r,true)} className="rounded-xl bg-[#167bd1] py-2.5 text-xs font-black"><Check size={14} className="mr-1 inline"/>Accept</button><button disabled={busy===r.id} onClick={()=>void respond(r,false)} className="rounded-xl border border-[#36506b] py-2.5 text-xs font-black"><X size={14} className="mr-1 inline"/>Decline</button></div></div>)}</div></section>:null}
 <section className="mt-7"><div className="mb-3 flex items-end justify-between"><div><h2 className="text-lg font-black">Players ready now</h2><p className="mt-1 text-xs text-[#7892ac]">Only real MatchUp users who enabled Ready Player appear here.</p></div><Swords size={20} className="text-[#47a8ff]"/></div>{loading?<div className="py-12 text-center text-sm text-[#7892ac]">Checking who is ready…</div>:players.length?<div className="space-y-2">{players.map(p=>{const sent=outgoing.some(r=>r.opponent_id===p.id);return <div key={p.id} className="flex items-center gap-3 rounded-2xl border border-[#18365f] bg-[#071426] p-3"><MatchUpAvatar profile={p} size="md" alt={nameOf(p)}/><div className="min-w-0 flex-1"><p className="truncate font-black">{nameOf(p)}</p><p className="mt-1 text-xs text-[#7892ac]">Ready to play</p></div>{sent?<span className="rounded-xl border border-[#36506b] px-3 py-2 text-xs font-black text-[#9ab0c4]">Pending</span>:<button disabled={busy===p.id} onClick={()=>void challenge(p)} className="flex items-center gap-1.5 rounded-xl bg-[#167bd1] px-3 py-2.5 text-xs font-black disabled:opacity-50"><Swords size={14}/>{busy===p.id?"Sending…":"Challenge"}</button>}</div>})}</div>:<div className="rounded-3xl border border-dashed border-[#18365f] bg-[#071426] p-9 text-center"><Swords size={28} className="mx-auto text-[#47a8ff]"/><p className="mt-3 font-black">No one else is ready right now</p><p className="mt-1 text-sm text-[#7892ac]">Turn on Ready Player and come back when another player is available.</p></div>}</section></div></main>;
}
