import { ArrowRight, CalendarDays, Copy, Search, ShieldCheck, Users } from "lucide-react";
import { Navigation } from "../components/navigation";
const tournaments=[
 {name:"Lagos Elite Cup",tag:"FEATURED",players:"18 / 32 players",date:"Sat, 14 Sep · 7:00 PM",format:"Knockout",color:"from-[#ccf95a] to-[#77b84c]"},
 {name:"Weekend eFootball League",tag:"PINNED",players:"12 / 16 players",date:"Sun, 15 Sep · 4:30 PM",format:"League",color:"from-[#69cae7] to-[#2355a7]"},
 {name:"Road to Glory",tag:"BOOSTED",players:"28 / 64 players",date:"Fri, 20 Sep · 8:00 PM",format:"Group + KO",color:"from-[#dd8cda] to-[#79277e]"}
];
export default function Home() { return <main className="shell"><Navigation/><section className="grid-bg relative overflow-hidden rounded-[28px] px-6 py-9 text-white md:px-12 md:py-14"><div className="relative z-10 max-w-2xl"><p className="mb-4 text-xs font-black tracking-[.2em] text-[#c9f950]">THE HOME OF eFOOTBALL TOURNAMENTS</p><h1 className="text-4xl font-black leading-[.95] tracking-tight md:text-6xl">Find your next<br/><span className="text-[#c9f950]">competition.</span></h1><p className="mt-5 max-w-md text-sm leading-6 text-[#c2cec5]">Create, discover and run competitive eFootball tournaments—all in one match-ready place.</p><div className="mt-7 flex flex-wrap gap-3"><button className="rounded-xl bg-[#c9f950] px-5 py-3 text-sm font-black text-[#07170f]">CREATE TOURNAMENT</button><button className="rounded-xl border border-white/25 px-5 py-3 text-sm font-bold">FIND TOURNAMENT</button></div></div><div className="absolute -right-12 -top-20 size-72 rounded-full border-[28px] border-[#c9f950]/15"/></section>
<section className="mt-8"><div className="mb-4 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-[#758077]">Discover</p><h2 className="text-2xl font-black">Tournaments made to compete</h2></div><button className="pill flex items-center gap-2"><Search size={14}/> Search</button></div><div className="grid gap-4 md:grid-cols-3">{tournaments.map(t=><article className="card overflow-hidden" key={t.name}><div className={`h-28 bg-gradient-to-br ${t.color} p-4`}><span className="rounded-full bg-black/25 px-2 py-1 text-[10px] font-black tracking-wider text-white">{t.tag}</span><div className="mt-6 text-lg font-black text-white">{t.name}</div></div><div className="p-4"><div className="flex justify-between text-xs text-[#657066]"><span className="flex gap-1"><Users size={14}/>{t.players}</span><span>{t.format}</span></div><p className="mt-3 flex items-center gap-2 text-sm font-bold"><CalendarDays size={15} className="text-[#5e9d39]"/>{t.date}</p><button className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-[#07170f] py-2.5 text-xs font-black text-white">VIEW TOURNAMENT <ArrowRight size={14}/></button></div></article>)}</div></section>
<section className="mt-8 grid gap-4 md:grid-cols-[1.5fr_1fr]"><div className="card p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-[#758077]">Quick entry</p><h2 className="text-xl font-black">Have a tournament ID?</h2></div><Copy size={20} className="text-[#6d786f]"/></div><div className="mt-4 flex gap-2"><input aria-label="Tournament ID" placeholder="e.g. MU-7K2P" className="min-w-0 flex-1 rounded-xl border border-[#dce6d8] px-4 py-3 text-sm outline-none focus:border-[#5e9d39]"/><button className="rounded-xl bg-[#c9f950] px-4 text-xs font-black">JOIN</button></div></div><div className="rounded-[20px] bg-[#e7f4dd] p-5"><ShieldCheck className="text-[#438b28]"/><h2 className="mt-3 text-lg font-black">Built for fair play.</h2><p className="mt-1 text-sm leading-5 text-[#587152]">Submit results, confirm scores and keep every match moving.</p></div></section>
<section className="mt-8"><p className="text-xs font-bold uppercase tracking-wider text-[#758077]">From the community</p><h2 className="mb-4 text-2xl font-black">Trending this week</h2><div className="grid gap-3 md:grid-cols-3">{["My 4-3-3 possession setup", "Last-minute winner in Elite Cup", "Who is ready for tonight’s bracket?"].map((post,i)=><article className="card p-4" key={post}><div className={`mb-4 h-24 rounded-xl ${i===0?"bg-[#d9e8d0]":i===1?"bg-[#d3e9ef]":"bg-[#ece1d4]"}`}/><p className="font-bold">{post}</p><p className="mt-2 text-xs text-[#758077]">Community · {12+i*7} comments</p></article>)}</div></section></main> }
