"use client";
import { useEffect, useMemo, useState } from "react";
import { Check, Forward, Loader2, X } from "lucide-react";
import { createBrowserSupabaseClient } from "../../lib/supabase/client";
type Profile={id:string;display_name:string|null;username:string|null;avatar_path?:string|null};
type Destination={id:string;kind:"friend"|"group";label:string;profile?:Profile|null};
export function ContentForwarder({open,onClose,contentUrl,title}:{open:boolean;onClose:()=>void;contentUrl:string;title:string}){
 const supabase=useMemo(()=>createBrowserSupabaseClient(),[]);const [destinations,setDestinations]=useState<Destination[]>([]);const [selected,setSelected]=useState<string[]>([]);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState("");
 useEffect(()=>{if(!open)return;let cancelled=false;const load=async()=>{const {data:auth}=await supabase.auth.getUser();if(!auth.user){if(!cancelled)setDestinations([]);return;}const uid=auth.user.id;const [{data:friends},{data:groups},{data:general}]=await Promise.all([supabase.from("friendships").select("user_id,friend_id").eq("status","accepted").or(`user_id.eq.${uid},friend_id.eq.${uid}`),supabase.from("chat_group_members").select("group_id,chat_groups(id,name,kind)").eq("user_id",uid),supabase.from("chat_groups").select("id,name,kind").eq("kind","general").maybeSingle()]);const friendIds=((friends||[]) as any[]).map(r=>r.user_id===uid?r.friend_id:r.user_id);const {data:profiles}=friendIds.length?await supabase.from("profiles").select("id,display_name,username,avatar_path").in("id",friendIds):{data:[]};const ds:Destination[]=(profiles||[]).map((p:any)=>({id:`friend:${p.id}`,kind:"friend",label:p.display_name||p.username||"MatchUp Player",profile:p}));const gs=(groups||[]).map((r:any)=>r.chat_groups).filter(Boolean).filter((g:any)=>g.kind==="group").map((g:any)=>({id:`group:${g.id}`,kind:"group" as const,label:g.name}));if(general)gs.unshift({id:`group:${(general as any).id}`,kind:"group",label:"General"});if(!cancelled){setDestinations([...ds,...gs]);setSelected([]);setNotice("");}};void load();return()=>{cancelled=true;};},[open,supabase]);
 if(!open)return null;const toggle=(id:string)=>setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);const send=async()=>{if(!selected.length)return;setBusy(true);setNotice("");const {data:auth}=await supabase.auth.getUser();if(!auth.user){setBusy(false);setNotice("Sign in to forward content.");return;}try{for(const key of selected){const [kind,id]=key.split(":");let groupId=id;if(kind==="friend"){const {data,error}=await supabase.rpc("get_or_create_private_chat",{p_friend_id:id});if(error||!data)throw error||new Error("Could not open private chat");groupId=data as string;}const body=`${title}\n${contentUrl}`;const {error}=await supabase.from("chat_messages").insert({group_id:groupId,sender_id:auth.user.id,body});if(error)throw error;}setNotice(`Forwarded to ${selected.length} ${selected.length===1?"destination":"destinations"}.`);setSelected([]);}catch(e){setNotice(e instanceof Error?e.message:"Could not forward this content.");}finally{setBusy(false);}};
 return <div className="fixed inset-0 z-[100] flex items-end justify-center bg-black/65 p-3 backdrop-blur-sm sm:items-center" role="dialog" aria-modal="true"><div className="w-full max-w-lg overflow-hidden rounded-[28px] border border-[#194b7c] bg-[#08182b] shadow-[0_28px_90px_rgba(0,0,0,.65)]"><div className="flex items-center justify-between border-b border-white/5 px-5 py-4"><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#47a8ff]">Forward</p><h2 className="mt-1 text-lg font-black text-white">Send to friends or groups</h2></div><button type="button" onClick={onClose} className="icon-button" aria-label="Close"><X size={18}/></button></div><div className="max-h-[55vh] overflow-y-auto p-4"><div className="mb-4 rounded-2xl border border-[#18365f] bg-[#071426] p-3"><p className="truncate text-sm font-black text-white">{title}</p><p className="mt-1 truncate text-xs text-[#7892ac]">{contentUrl}</p></div>{destinations.length?<div className="grid gap-2">{destinations.map(d=><button key={d.id} type="button" onClick={()=>toggle(d.id)} className={`flex items-center gap-3 rounded-2xl border p-3 text-left transition ${selected.includes(d.id)?"border-[#2497ff] bg-[#0b3154]":"border-[#18365f] bg-[#071426]"}`}><span className="grid size-10 shrink-0 place-items-center overflow-hidden rounded-full bg-[#0b3154] text-xs font-black text-[#70c1ff]">{d.profile?.avatar_path?<img src={d.profile.avatar_path} alt="" className="size-full object-cover"/>:d.kind==="group"?"G":(d.profile?.display_name||d.profile?.username||"M").slice(0,1).toUpperCase()}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-black text-white">{d.label}</span><span className="block text-[10px] uppercase tracking-[.12em] text-[#7892ac]">{d.kind}</span></span>{selected.includes(d.id)?<Check size={18} className="text-[#70c1ff]"/>:null}</button>)}</div>:<p className="py-10 text-center text-sm text-[#7892ac]">No eligible friends or joined groups yet.</p>}</div><div className="border-t border-white/5 p-4">{notice?<p role="status" className="mb-3 text-xs font-bold text-[#9bd3ff]">{notice}</p>:null}<button type="button" disabled={!selected.length||busy} onClick={()=>void send()} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-[#167bd1] px-4 py-3.5 text-sm font-black text-white disabled:opacity-50">{busy?<Loader2 size={17} className="animate-spin"/>:<Forward size={17}/>}Forward{selected.length?` to ${selected.length}`:""}</button></div></div></div>;
}
