"use client";
import { useEffect, useMemo, useState } from "react";
type AvatarProfile={id?:string;display_name?:string|null;username?:string|null;avatar_path?:string|null};
type Props={profile?:AvatarProfile|null;size?:"sm"|"md"|"lg";alt?:string;className?:string;group?:boolean};
const sizeClass={sm:"size-10",md:"size-12",lg:"size-16"};const palettes=[["#123a63","#43a8ff","#d8f0ff"],["#183f35","#35c58a","#d8fff0"],["#49321c","#ffb454","#fff0d5"],["#3d244d","#c87cff","#f3ddff"],["#173b4b","#48d1e5","#dcfbff"]];
function hash(value:string){let h=0;for(let i=0;i<value.length;i++)h=(h*31+value.charCodeAt(i))|0;return Math.abs(h)}function label(p?:AvatarProfile|null){return p?.display_name||p?.username||"MatchUp Player"}
function cacheKey(src:string){return `matchup:avatar-color:${src}`}function getCached(src:string){try{return localStorage.getItem(cacheKey(src))}catch{return null}}function putCached(src:string,c:string){try{localStorage.setItem(cacheKey(src),c)}catch{}}
export function MatchUpAvatar({profile,size="md",alt,className="",group=false}:Props){const[failed,setFailed]=useState(false),[accent,setAccent]=useState<string|null>(null);const key=profile?.id||profile?.avatar_path||"matchup-default",palette=palettes[hash(key)%palettes.length],name=label(profile);useEffect(()=>{setFailed(false);const src=profile?.avatar_path;if(!src||!/^https?:\/\//i.test(src))return;const cached=getCached(src);if(cached){setAccent(cached);return}let cancelled=false;const img=new Image();img.crossOrigin="anonymous";img.onload=()=>{if(cancelled)return;try{const canvas=document.createElement("canvas");canvas.width=24;canvas.height=24;const ctx=canvas.getContext("2d",{willReadFrequently:true});if(!ctx)return;ctx.drawImage(img,0,0,24,24);const pixels=ctx.getImageData(0,0,24,24).data,bins=new Map<string,number>();for(let i=0;i<pixels.length;i+=4){const a=pixels[i+3],r=pixels[i],g=pixels[i+1],b=pixels[i+2],v=(r+g+b)/3,s=Math.max(r,g,b)-Math.min(r,g,b);if(a<160||v>235||v<22||s<28)continue;const q=[Math.round(r/24)*24,Math.round(g/24)*24,Math.round(b/24)*24],k=q.join(",");bins.set(k,(bins.get(k)||0)+1+s/255)}const winner=[...bins.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0];if(!winner)return;let[r,g,b]=winner.split(",").map(Number);const lift=Math.max(r,g,b)<115?1.45:1;const rgb=[r*lift,g*lift,b*lift].map(v=>Math.min(255,Math.round(v))),color=`rgb(${rgb[0]}, ${rgb[1]}, ${rgb[2]})`;putCached(src,color);if(!cancelled)setAccent(color)}catch{}};img.onerror=()=>{if(!cancelled)setFailed(true)};img.src=src;return()=>{cancelled=true}},[profile?.avatar_path]);const background=useMemo(()=>`linear-gradient(145deg, ${palette[0]}, ${palette[1]})`,[palette]);return <span className={`relative inline-grid shrink-0 overflow-hidden rounded-[24%] ${sizeClass[size]} ${className}`} style={{background}}>{profile?.avatar_path&&!failed?<img src={profile.avatar_path} alt={alt??name} className="size-full object-cover" loading="lazy" onError={()=>setFailed(true)}/>:<DefaultAvatar group={group} palette={palette} label={name}/>} {accent&&<span aria-hidden="true" className="pointer-events-none absolute inset-0 rounded-[24%] ring-1" style={{boxShadow:`inset 0 0 0 1px ${accent}`}}/>}</span>}
function DefaultAvatar({group,palette,label}:{group:boolean;palette:string[];label:string}){const n=hash(label),skin=["#f4c7a1","#9d6545","#6b3e2a","#e5ad82"][n%4],shirt=["#eaf6ff","#42a8ff","#35c58a","#ffb454"][n%4];if(group)return <svg viewBox="0 0 100 100" className="size-full" aria-label="MatchUp group avatar" role="img"><rect width="100" height="100" rx="24" fill={palette[0]}/><circle cx="33" cy="42" r="18" fill={skin}/><circle cx="67" cy="42" r="18" fill={skin}/><circle cx="50" cy="30" r="16" fill="#f0b58e"/><path d="M13 91c2-18 13-27 28-27s26 9 28 27" fill={shirt}/><path d="M39 91c2-18 13-27 28-27s24 9 26 27" fill={palette[1]}/><path d="M28 91c2-14 10-21 22-21s20 7 22 21" fill="#eaf6ff"/></svg>;return <svg viewBox="0 0 100 100" className="size-full" aria-label="MatchUp default avatar" role="img"><rect width="100" height="100" rx="24" fill={palette[0]}/><circle cx="50" cy="40" r="22" fill={skin}/><path d="M28 35c2-18 13-27 23-27 13 0 23 10 22 29-7-7-14-10-23-10-7 0-15 3-22 8Z" fill="#172231"/><circle cx="42" cy="41" r="3" fill="#172231"/><circle cx="58" cy="41" r="3" fill="#172231"/><path d="M39 52c7 6 15 6 22 0" fill="none" stroke="#172231" strokeWidth="3" strokeLinecap="round"/><path d="M24 100c1-25 12-35 26-35s25 10 26 35" fill={shirt}/><path d="M44 66l6 10 6-10" fill="#fff" opacity=".9"/></svg>}
