export type BuiltinTeam = { id: string; fullName: string; shortName: string; country: string; league: string; crestUrl: string; searchKeywords: string[]; };

const crest = (slug: string) => `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(slug)}?width=220`;
const t = (id: string, fullName: string, shortName: string, country: string, league: string, file: string) => ({ id, fullName, shortName, country, league, crestUrl: crest(file), searchKeywords: [fullName, shortName, country, league] });

export const builtinTeams: BuiltinTeam[] = [
  t("arsenal", "Arsenal", "ARS", "England", "Premier League", "Arsenal_FC.svg"),
  t("chelsea", "Chelsea", "CHE", "England", "Premier League", "Chelsea_FC.svg"),
  t("liverpool", "Liverpool", "LIV", "England", "Premier League", "Liverpool_FC.svg"),
  t("man-city", "Manchester City", "MCI", "England", "Premier League", "Manchester_City_FC_badge.svg"),
  t("man-united", "Manchester United", "MUN", "England", "Premier League", "Manchester_United_FC_crest.svg"),
  t("tottenham", "Tottenham Hotspur", "TOT", "England", "Premier League", "Tottenham_Hotspur_FC.svg"),
  t("newcastle", "Newcastle United", "NEW", "England", "Premier League", "Newcastle_United_Logo.svg"),
  t("aston-villa", "Aston Villa", "AVL", "England", "Premier League", "Aston_Villa_FC_new_crest.svg"),
  t("west-ham", "West Ham United", "WHU", "England", "Premier League", "West_Ham_United_FC.svg"),
  t("everton", "Everton", "EVE", "England", "Premier League", "Everton_FC_logo.svg"),
  t("nottingham", "Nottingham Forest", "NFO", "England", "Premier League", "Nottingham_Forest_F.C._logo.svg"),
  t("brighton", "Brighton & Hove Albion", "BHA", "England", "Premier League", "Brighton_%26_Hove_Albion_logo.svg"),
  t("crystal-palace", "Crystal Palace", "CRY", "England", "Premier League", "Crystal_Palace_FC_logo.svg"),
  t("fulham", "Fulham", "FUL", "England", "Premier League", "Fulham_FC.svg"),
  t("wolves", "Wolverhampton Wanderers", "WOL", "England", "Premier League", "Wolverhampton_Wanderers_FC_crest.svg"),
  t("barcelona", "FC Barcelona", "BAR", "Spain", "La Liga", "FC_Barcelona.svg"),
  t("real-madrid", "Real Madrid", "RMA", "Spain", "La Liga", "Real_Madrid_CF.svg"),
  t("atletico", "Atlético Madrid", "ATM", "Spain", "La Liga", "Atletico_Madrid_2017_logo.svg"),
  t("sevilla", "Sevilla FC", "SEV", "Spain", "La Liga", "Sevilla_FC_logo.svg"),
  t("valencia", "Valencia CF", "VAL", "Spain", "La Liga", "Valencia_CF_Logo.svg"),
  t("villarreal", "Villarreal CF", "VIL", "Spain", "La Liga", "Villarreal_CF_logo-en.svg"),
  t("athletic", "Athletic Club", "ATH", "Spain", "La Liga", "Athletic_Club_Bilbao_logo.svg"),
  t("real-betis", "Real Betis", "BET", "Spain", "La Liga", "Real_betis_logo.svg"),
  t("real-sociedad", "Real Sociedad", "RSO", "Spain", "La Liga", "Real_Sociedad_logo.svg"),
  t("girona", "Girona FC", "GIR", "Spain", "La Liga", "Girona_FC_Logo.svg"),
  t("inter", "Inter Milan", "INT", "Italy", "Serie A", "Inter_Milan.svg"),
  t("ac-milan", "AC Milan", "MIL", "Italy", "Serie A", "AC_Milan_Logo.svg"),
  t("juventus", "Juventus", "JUV", "Italy", "Serie A", "Juventus_FC_2017_logo.svg"),
  t("napoli", "Napoli", "NAP", "Italy", "Serie A", "SSC_Napoli_2016_logo.svg"),
  t("roma", "AS Roma", "ROM", "Italy", "Serie A", "AS_Roma_logo.svg"),
  t("lazio", "SS Lazio", "LAZ", "Italy", "Serie A", "S.S._Lazio_badge.svg"),
  t("atalanta", "Atalanta", "ATA", "Italy", "Serie A", "Atalanta_BC_logo.svg"),
  t("bayern", "Bayern Munich", "BAY", "Germany", "Bundesliga", "FC_Bayern_München_logo.svg"),
  t("dortmund", "Borussia Dortmund", "BVB", "Germany", "Bundesliga", "Borussia_Dortmund_logo.svg"),
  t("leverkusen", "Bayer Leverkusen", "B04", "Germany", "Bundesliga", "Bayer_04_Leverkusen_logo.svg"),
  t("leipzig", "RB Leipzig", "RBL", "Germany", "Bundesliga", "RB_Leipzig_Logo_2014.svg"),
  t("frankfurt", "Eintracht Frankfurt", "SGE", "Germany", "Bundesliga", "Eintracht_Frankfurt_Logo.svg"),
  t("psg", "Paris Saint-Germain", "PSG", "France", "Ligue 1", "Paris_Saint-Germain_F.C..svg"),
  t("marseille", "Olympique de Marseille", "OM", "France", "Ligue 1", "Olympique_Marseille_logo.svg"),
  t("lyon", "Olympique Lyonnais", "LYO", "France", "Ligue 1", "Olympique_Lyonnais_logo.svg"),
  t("monaco", "AS Monaco", "ASM", "France", "Ligue 1", "AS_Monaco_FC.svg"),
  t("ajax", "Ajax", "AJA", "Netherlands", "Eredivisie", "AFC_Ajax.svg"),
  t("psv", "PSV Eindhoven", "PSV", "Netherlands", "Eredivisie", "PSV_Eindhoven_logo.svg"),
  t("feyenoord", "Feyenoord", "FEY", "Netherlands", "Eredivisie", "Feyenoord_logo_since_1997.svg"),
  t("benfica", "SL Benfica", "BEN", "Portugal", "Primeira Liga", "SL_Benfica_logo.svg"),
  t("porto", "FC Porto", "FCP", "Portugal", "Primeira Liga", "FC_Porto.svg"),
  t("sporting", "Sporting CP", "SCP", "Portugal", "Primeira Liga", "Sporting_Clube_de_Portugal.svg"),
  t("celtic", "Celtic", "CEL", "Scotland", "Scottish Premiership", "Celtic_FC.svg"),
  t("rangers", "Rangers", "RAN", "Scotland", "Scottish Premiership", "Rangers_FC.svg"),
  t("galatasaray", "Galatasaray", "GAL", "Türkiye", "Süper Lig", "Galatasaray_Sports_Club_Logo.svg"),
  t("fenerbahce", "Fenerbahçe", "FEN", "Türkiye", "Süper Lig", "Fenerbahçe.svg"),
  t("club-brugge", "Club Brugge", "BRU", "Belgium", "Belgian Pro League", "Club_Brugge_KV_logo.svg"),
  t("red-star", "Red Star Belgrade", "RSB", "Serbia", "Serbian SuperLiga", "FK_Crvena_zvezda_crest.svg"),
  t("dinamo-zagreb", "Dinamo Zagreb", "DZG", "Croatia", "HNL", "GNK_Dinamo_Zagreb_logo.svg"),
  t("copenhagen", "FC Copenhagen", "FCK", "Denmark", "Superliga", "FC_Copenhagen_logo.svg"),
  t("salzburg", "Red Bull Salzburg", "RBS", "Austria", "Austrian Bundesliga", "FC_Red_Bull_Salzburg_logo.svg"),
  t("shakhtar", "Shakhtar Donetsk", "SHK", "Ukraine", "Ukrainian Premier League", "FC_Shakhtar_Donetsk.svg"),
  t("dynamo-kyiv", "Dynamo Kyiv", "DYN", "Ukraine", "Ukrainian Premier League", "FC_Dynamo_Kyiv_logo.svg"),
  t("flamengo", "Flamengo", "FLA", "Brazil", "Brasileirão", "CR_Flamengo_logo.svg"),
  t("palmeiras", "Palmeiras", "PAL", "Brazil", "Brasileirão", "Palmeiras_logo.svg"),
  t("corinthians", "Corinthians", "COR", "Brazil", "Brasileirão", "Sport_Club_Corinthians_Paulista_crest.svg"),
  t("santos", "Santos", "SAN", "Brazil", "Brasileirão", "Santos_FC_logo.svg"),
  t("boca", "Boca Juniors", "BOC", "Argentina", "Primera División", "Boca_Juniors_logo18.svg"),
  t("river", "River Plate", "RIV", "Argentina", "Primera División", "Club_Atlético_River_Plate_logo.svg"),
  t("inter-miami", "Inter Miami", "MIA", "United States", "MLS", "Inter_Miami_CF_logo.svg"),
  t("la-galaxy", "LA Galaxy", "LAG", "United States", "MLS", "LA_Galaxy_logo.svg"),
  t("lafc", "Los Angeles FC", "LAFC", "United States", "MLS", "Los_Angeles_FC_logo.svg"),
  t("nycfc", "New York City FC", "NYC", "United States", "MLS", "New_York_City_FC_logo.svg"),
  t("al-ahly", "Al Ahly", "AHL", "Egypt", "Egyptian Premier League", "Al_Ahly_SC_logo.svg"),
  t("zamalek", "Zamalek", "ZAM", "Egypt", "Egyptian Premier League", "Zamalek_SC_logo.svg"),
  t("esperance", "Espérance de Tunis", "EST", "Tunisia", "Tunisian Ligue Professionnelle 1", "Espérance_Sportive_de_Tunis.svg"),
  t("wydad", "Wydad AC", "WAC", "Morocco", "Botola", "Wydad_AC.svg"),
  t("esperance-nigeria", "Enyimba", "ENY", "Nigeria", "Nigeria Premier Football League", "Enyimba_FC_logo.svg"),
  t("plateau", "Plateau United", "PLU", "Nigeria", "Nigeria Premier Football League", "Plateau_United_FC_logo.svg"),
  t("rivers", "Rivers United", "RIVU", "Nigeria", "Nigeria Premier Football League", "Rivers_United_FC_logo.svg"),
  t("remang", "Remo Stars", "REM", "Nigeria", "Nigeria Premier Football League", "Remo_Stars_FC_logo.svg"),
  t("shooting-stars", "Shooting Stars", "3SC", "Nigeria", "Nigeria Premier Football League", "Shooting_Stars_Sports_Club_logo.svg"),
  t("sunshine", "Sunshine Stars", "SUN", "Nigeria", "Nigeria Premier Football League", "Sunshine_Stars_F.C._logo.svg"),
  t("kano-pillars", "Kano Pillars", "KAN", "Nigeria", "Nigeria Premier Football League", "Kano_Pillars_FC_logo.svg"),
  t("heartland", "Heartland FC", "HEA", "Nigeria", "Nigeria Premier Football League", "Heartland_FC_logo.svg"),
  t("warri-wolves", "Warri Wolves", "WAR", "Nigeria", "Nigeria", "Warri_Wolves_FC_logo.svg"),
  t("kwara-united", "Kwara United", "KWA", "Nigeria", "Nigeria Premier Football League", "Kwara_United_FC_logo.svg"),
  t("pln-legacy", "Lobi Stars", "LOB", "Nigeria", "Nigeria Premier Football League", "Lobi_Stars_FC_logo.svg"),
  t("eagles", "Nigeria", "NGA", "Nigeria", "National Team", "Flag_of_Nigeria.svg"),
  t("brazil", "Brazil", "BRA", "Brazil", "National Team", "CBF_Brazil_logo.svg"),
  t("france", "France", "FRA", "France", "National Team", "Fédération_Française_de_Football_logo.svg"),
  t("england", "England", "ENG", "England", "National Team", "England_crest_2009.svg"),
  t("argentina", "Argentina", "ARG", "Argentina", "National Team", "AFA_logo.svg"),
  t("spain", "Spain", "ESP", "Spain", "National Team", "Spain_national_football_team_crest.svg"),
  t("germany", "Germany", "GER", "Germany", "National Team", "German_Football_Association_logo.svg"),
  t("portugal", "Portugal", "POR", "Portugal", "National Team", "Portuguese_Football_Federation_crest.svg"),
  t("netherlands", "Netherlands", "NED", "Netherlands", "National Team", "Royal_Netherlands_Football_Association_logo.svg"),
];

export const teamLeagues = [...new Set(builtinTeams.map((t) => t.league))].sort();
export const teamCountries = [...new Set(builtinTeams.map((t) => t.country))].sort();
