-- MatchUp social/ready-player/match-chat completion.
-- Applied to the connected Supabase project as migration complete_social_ready_match_chat_20260913.
alter table public.profiles add column if not exists ready_player_enabled boolean not null default false;
alter table public.profiles add column if not exists ready_player_updated_at timestamptz;
alter table public.chat_groups drop constraint if exists chat_groups_kind_check;
alter table public.chat_groups add constraint chat_groups_kind_check check (kind = any (array['general','private','group','match']));
create table if not exists public.match_requests (
 id uuid primary key default gen_random_uuid(), requester_id uuid not null references public.profiles(id) on delete cascade, opponent_id uuid not null references public.profiles(id) on delete cascade,
 status text not null default 'pending' check(status in ('pending','accepted','declined','cancelled')), created_at timestamptz not null default now(), responded_at timestamptz,
 constraint match_requests_not_self check(requester_id<>opponent_id)
);
create unique index if not exists match_requests_one_pending_pair on public.match_requests(least(requester_id,opponent_id),greatest(requester_id,opponent_id)) where status='pending';
create index if not exists match_requests_opponent_status_idx on public.match_requests(opponent_id,status,created_at desc);
create index if not exists match_requests_requester_status_idx on public.match_requests(requester_id,status,created_at desc);
create table if not exists public.matches (
 id uuid primary key default gen_random_uuid(), match_request_id uuid not null unique references public.match_requests(id) on delete cascade,
 player_a_id uuid not null references public.profiles(id) on delete cascade, player_b_id uuid not null references public.profiles(id) on delete cascade,
 status text not null default 'active' check(status in ('active','completed','cancelled')), created_at timestamptz not null default now(), constraint matches_not_self check(player_a_id<>player_b_id)
);
create index if not exists matches_player_a_idx on public.matches(player_a_id,created_at desc); create index if not exists matches_player_b_idx on public.matches(player_b_id,created_at desc);
create table if not exists public.match_conversations (
 match_id uuid primary key references public.matches(id) on delete cascade, conversation_id uuid not null unique references public.chat_groups(id) on delete cascade,
 status text not null default 'active' check(status in ('active','closed')), created_at timestamptz not null default now()
);
alter table public.match_requests enable row level security; alter table public.matches enable row level security; alter table public.match_conversations enable row level security;
create or replace function public.is_match_participant(p_match_id uuid,p_user_id uuid default auth.uid()) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.matches m where m.id=p_match_id and (m.player_a_id=coalesce(p_user_id,auth.uid()) or m.player_b_id=coalesce(p_user_id,auth.uid()))); $$;
revoke all on function public.is_match_participant(uuid,uuid) from public; grant execute on function public.is_match_participant(uuid,uuid) to authenticated;
drop policy if exists match_requests_select_participant on public.match_requests; create policy match_requests_select_participant on public.match_requests for select to authenticated using(requester_id=auth.uid() or opponent_id=auth.uid());
drop policy if exists match_requests_update_participant on public.match_requests; create policy match_requests_update_participant on public.match_requests for update to authenticated using(opponent_id=auth.uid() or requester_id=auth.uid()) with check(opponent_id=auth.uid() or requester_id=auth.uid());
drop policy if exists matches_select_participant on public.matches; create policy matches_select_participant on public.matches for select to authenticated using(player_a_id=auth.uid() or player_b_id=auth.uid());
drop policy if exists match_conversations_select_participant on public.match_conversations; create policy match_conversations_select_participant on public.match_conversations for select to authenticated using(public.is_match_participant(match_id));
drop policy if exists match_conversations_update_participant on public.match_conversations; create policy match_conversations_update_participant on public.match_conversations for update to authenticated using(public.is_match_participant(match_id)) with check(public.is_match_participant(match_id));
create or replace function public.set_ready_player(p_enabled boolean) returns boolean language plpgsql security definer set search_path=public as $$ begin if auth.uid() is null then raise exception 'Not authenticated'; end if; update public.profiles set ready_player_enabled=p_enabled,ready_player_updated_at=now() where id=auth.uid(); return p_enabled; end; $$;
revoke all on function public.set_ready_player(boolean) from public; grant execute on function public.set_ready_player(boolean) to authenticated;
create or replace function public.send_match_request(p_opponent_id uuid) returns uuid language plpgsql security definer set search_path=public as $$ declare v_id uuid; begin if auth.uid() is null then raise exception 'Not authenticated'; end if; if p_opponent_id is null or p_opponent_id=auth.uid() then raise exception 'Choose another ready player'; end if; if not exists(select 1 from public.profiles where id=p_opponent_id and ready_player_enabled) then raise exception 'That player is no longer marked ready'; end if; if not exists(select 1 from public.profiles where id=auth.uid() and ready_player_enabled) then raise exception 'Turn on Ready Player before sending a match request'; end if; if exists(select 1 from public.match_requests where status='pending' and ((requester_id=auth.uid() and opponent_id=p_opponent_id) or (requester_id=p_opponent_id and opponent_id=auth.uid()))) then raise exception 'A match request is already pending between you'; end if; if exists(select 1 from public.matches where status='active' and (player_a_id=auth.uid() or player_b_id=auth.uid())) then raise exception 'You already have an active match'; end if; insert into public.match_requests(requester_id,opponent_id) values(auth.uid(),p_opponent_id) returning id into v_id; insert into public.notifications(recipient_id,kind,payload) values(p_opponent_id,'match_request',jsonb_build_object('request_id',v_id,'requester_id',auth.uid())); return v_id; exception when unique_violation then raise exception 'A match request is already pending between you'; end; $$;
revoke all on function public.send_match_request(uuid) from public; grant execute on function public.send_match_request(uuid) to authenticated;
create or replace function public.respond_match_request(p_request_id uuid,p_accept boolean) returns uuid language plpgsql security definer set search_path=public as $$ declare r public.match_requests%rowtype; v_match uuid; v_group uuid; begin if auth.uid() is null then raise exception 'Not authenticated'; end if; select * into r from public.match_requests where id=p_request_id and status='pending' and opponent_id=auth.uid() for update; if not found then raise exception 'This match request is no longer pending'; end if; if not p_accept then update public.match_requests set status='declined',responded_at=now() where id=r.id; insert into public.notifications(recipient_id,kind,payload) values(r.requester_id,'match_request_declined',jsonb_build_object('request_id',r.id,'opponent_id',auth.uid())); return r.id; end if; if exists(select 1 from public.matches where status='active' and (player_a_id=auth.uid() or player_b_id=auth.uid())) then raise exception 'You already have an active match'; end if; update public.match_requests set status='accepted',responded_at=now() where id=r.id; insert into public.matches(match_request_id,player_a_id,player_b_id) values(r.id,r.requester_id,r.opponent_id) returning id into v_match; insert into public.chat_groups(name,created_by,kind,locked,member_limit) values('Match Chat',auth.uid(),'match',false,2) returning id into v_group; insert into public.chat_group_members(group_id,user_id,last_seen_at) values(v_group,r.requester_id,now()),(v_group,r.opponent_id,now()) on conflict do nothing; insert into public.match_conversations(match_id,conversation_id) values(v_match,v_group); update public.profiles set ready_player_enabled=false,ready_player_updated_at=now() where id in(r.requester_id,r.opponent_id); insert into public.notifications(recipient_id,kind,payload) values(r.requester_id,'match_request_accepted',jsonb_build_object('request_id',r.id,'match_id',v_match,'conversation_id',v_group)); return v_match; end; $$;
revoke all on function public.respond_match_request(uuid,boolean) from public; grant execute on function public.respond_match_request(uuid,boolean) to authenticated;
alter publication supabase_realtime add table public.match_requests;
alter publication supabase_realtime add table public.matches;
alter publication supabase_realtime add table public.match_conversations;
