"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, AtSign, Bell, Check, CheckCheck, Forward, Heart, Link2, MessageCircle, MoreHorizontal, Trophy, UserPlus, UsersRound, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { createBrowserSupabaseClient } from "../../lib/supabase/client";

type NotificationRow={id:string;recipient_id:string;kind:string;payload:Record<string,unknown>|null;read_at:string|null;created_at:string};
type Profile={id:string;display_name:string|null;username:string|null;avatar_path:string|null};
type ViewNotification=NotificationRow&{actor?:Profile|null;message:string;href?:string|null;thumbnail?:string|null;postBody?:string|null};
type InviteModal={kind:"group"|"tournament";notification:ViewNotification;group?:{id:string;name:string;image_path:string|null;member_count:number};tournament?:{id:string;name:string;description:string|null;starts_at:string|null;game_title:string|null;prize_pool:number|null};inviter?:Profile|null;participantId?:string};

function iconForKind(kind:string){if(kind.includes("like"))return Heart;if(kind.includes("comment"))return MessageCircle;if(kind.includes("tag"))return AtSign;if(kind.includes("link"))return Link2;if(kind.startsWith("friend"))return UserPlus;if(kind.startsWith("group"))return UsersRound;if(kind.includes("tournament"))return Trophy;return Forward;}
function payloadString(payload:Record<string,unknown>|null,key:string){const v=payload?.[key];return typeof v==="string"?v:null;}
function buildHref(row:NotificationRow){const explicit=payloadString(row.payload,"href");if(explicit)return explicit;const type=payloadString(row.payload,"entity_type");const id=payloadString(row.payload,"entity_id");if(!id)return null;if(type==="tournament")return `/tournaments/${id}`;if(type==="post")return `/feeds?post=${id}`;if(type==="profile")return `/leaderboard?add=friends&user=${id}`;if(type==="group")return `/leaderboard?group=${id}`;return null;}
function relativeTime(value:string){const minutes=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/60000));if(minutes<1)return "Just now";if(minutes<60)return `${minutes}m ago`;const hours=Math.floor(minutes/60);if(hours<24)return `${hours}h ago`;const days=Math.floor(hours/24);if(days<7)return `${days}d ago`;return new Date(value).toLocaleDateString(undefined,{month:"short",day:"numeric"});}
function absoluteDate(value:string){return new Date(value).toLocaleDateString(undefined,{year:"numeric",month:"long",day:"numeric"});}
function nameOf(p?:Profile|null){return p?.display_name||p?.username||"MatchUp player";}

export function NotificationsPage(){
 const router=useRouter();const supabase=useMemo(()=>createBrowserSupabaseClient(),[]);const [notifications,setNotifications]=useState<ViewNotification[]>([]);const [loading,setLoading]=useState(true);const [signedIn,setSignedIn]=useState(true);const [menuOpen,setMenuOpen]=useState(false);const [invite,setInvite]=useState<InviteModal|null>(null);const [working,setWorking]=useState(false);const [error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);const {data:auth}=await supabase.auth.getUser();if(!auth.user){setSignedIn(false);setNotifications([]);setLoading(false);return;}setSignedIn(true);const {data,error:e}=await supabase.from("notifications").select("id,recipient_id,kind,payload,read_at,created_at").eq("recipient_id",auth.user.id).order("created_at",{ascending:false}).limit(200);if(e){setNotifications([]);setLoading(false);return;}const rows=(data||[]) as NotificationRow[];const actorIds=Array.from(new Set(rows.map(r=>payloadString(r.payload,"actor_id")).filter((id):id is string=>Boolean(id))));let profiles:Profile[]=[];if(actorIds.length){const {data:profileData}=await supabase.from("profiles").select("id,display_name,username,avatar_path").in("id",actorIds);profiles=(profileData||[]) as Profile[];}const map=new Map(profiles.map(p=>[p.id,p]));setNotifications(rows.map(row=>{const actorId=payloadString(row.payload,"actor_id");const actor=actorId?map.get(actorId)||null:null;const fallback=row.kind.replaceAll("_"," ");return {...row,actor,message:payloadString(row.payload,"message")||fallback,href:buildHref(row),thumbnail:payloadString(row.payload,"thumbnail"),postBody:payloadString(row.payload,"post_body")};}));setLoading(false);},[supabase]);
 useEffect(()=>{void load();const channel=supabase.channel("user-notifications").on("postgres_changes",{event:"*",schema:"public",table:"notifications"},()=>void load()).subscribe();return()=>{void supabase.removeChannel(channel);};},[load,supabase]);
 const markRead=async(n:ViewNotification)=>{if(!n.read_at){const readAt=new Date().toISOString();const {error:e}=await supabase.from("notifications").update({read_at:readAt}).eq("id",n.id);if(!e)setNotifications(c=>c.map(x=>x.id===n.id?{...x,read_at:readAt}:x));}};
 const markAllRead=async()=>{const {data:auth}=await supabase.auth.getUser();if(!auth.user)return;const readAt=new Date().toISOString();const {error:e}=await supabase.from("notifications").update({read_at:readAt}).eq("recipient_id",auth.user.id).is("read_at",null);if(!e)setNotifications(c=>c.map(x=>({...x,read_at:x.read_at||readAt})));setMenuOpen(false);};
 const openNotification=async(n:ViewNotification)=>{await markRead(n);setError("");if(n.kind==="group_invitation"){const {data:auth}=await supabase.auth.getUser();if(!auth.user)return;const groupId=payloadString(n.payload,"entity_id");const inviterId=payloadString(n.payload,"actor_id");if(!groupId){setError("This invitation is no longer available.");return;}const [{data:g},{data:inviteRow}]=await Promise.all([supabase.from("chat_groups").select("id,name,image_path").eq("id",groupId).maybeSingle(),supabase.from("chat_group_invites").select("id,invited_by,status").eq("group_id",groupId).eq("invited_user_id",auth.user.id).eq("status","pending").order("created_at",{ascending:false}).limit(1).maybeSingle()]);if(!inviteRow||!g){setError("This group invitation is no longer pending.");return;}const {count}=await supabase.from("chat_group_members").select("user_id",{count:"exact",head:true}).eq("group_id",groupId);let inviter=n.actor||null;if(inviterId&&!inviter){const {data:p}=await supabase.from("profiles").select("id,display_name,username,avatar_path").eq("id",inviterId).maybeSingle();inviter=p as Profile|null;}setInvite({kind:"group",notification:n,group:{id:g.id,name:g.name,image_path:g.image_path||null,member_count:count||0},inviter});return;}if(n.kind==="tournament_invite"){const participantId=payloadString(n.payload,"participant_id");const tournamentId=payloadString(n.payload,"tournament_id")||payloadString(n.payload,"entity_id");if(!participantId){setError("This tournament invitation is no longer available.");return;}const {data:p}=await supabase.from("tournament_participants").select("id,tournament_id,invited_by,status").eq("id",participantId).maybeSingle();if(!p||p.status!=="pending"){setError("This tournament invitation is no longer pending.");return;}const {data:t}=await supabase.from("tournaments").select("id,name,description,starts_at,game_title,prize_pool").eq("id",tournamentId||p.tournament_id).maybeSingle();if(!t){setError("The tournament could not be found.");return;}let inviter=n.actor||null;if(p.invited_by){const {data:ip}=await supabase.from("profiles").select("id,display_name,username,avatar_path").eq("id",p.invited_by).maybeSingle();inviter=ip as Profile|null;}setInvite({kind:"tournament",notification:n,tournament:{id:t.id,name:t.name,description:t.description||null,starts_at:t.starts_at||null,game_title:t.game_title||null,prize_pool:t.prize_pool==null?null:Number(t.prize_pool)},inviter,participantId:p.id});return;}if(n.href)router.push(n.href);};
 const respond=async(accept:boolean)=>{if(!invite)return;setWorking(true);setError("");let e:null|string=null;if(invite.kind==="group"){const inviteId=payloadString(invite.notification.payload,"invite_id");let id=inviteId;if(!id){const {data:auth}=await supabase.auth.getUser();if(auth.user&&invite.group){const {data:row}=await supabase.from("chat_group_invites").select("id").eq("group_id",invite.group.id).eq("invited_user_id",auth.user.id).eq("status","pending").maybeSingle();id=row?.id||null;}}if(!id)e="This invitation is no longer pending.";else{const {error:rpcError}=await supabase.rpc("respond_chat_group_invite",{p_invite_id:id,p_accept:accept});e=rpcError?.message||null;}}else{if(!invite.participantId)e="This invitation is no longer pending.";else{const {error:rpcError}=await supabase.rpc("respond_tournament_invite",{p_participant_id:invite.participantId,p_accept:accept});e=rpcError?.message||null;}}if(e){setError(e);}else{setInvite(null);setNotifications(c=>c.filter(n=>n.id!==invite.notification.id));}setWorking(false);};
 const unread=notifications.filter(n=>!n.read_at).length;
 return <main className="app-shell min-h-screen pb-28"><div className="flex items-center justify-between gap-4"><div className="flex items-center gap-3"><button type="button" onClick={()=>router.push("/home")} aria-label="Back to Home" className="icon-button"><ArrowLeft size={18}/></button><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-[var(--accent)]">MatchUp</p><h1 className="text-2xl font-black text-white">Notifications</h1></div></div><div className="relative"><button type="button" onClick={()=>setMenuOpen(v=>!v)} aria-label="Notification options" aria-expanded={menuOpen} className="icon-button"><MoreHorizontal size={20}/></button>{menuOpen?<div className="absolute right-0 top-12 z-30 w-52 rounded-2xl border border-[var(--line)] bg-[var(--panel)] p-2 shadow-2xl"><button type="button" disabled={!unread} onClick={()=>void markAllRead()} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-bold text-white hover:bg-[var(--accent-soft)] disabled:cursor-not-allowed disabled:opacity-40"><CheckCheck size={16}/>Mark all as read</button></div>:null}</div></div>
 {!signedIn?<div className="surface-card mt-8 border-[var(--line)] p-8 text-center"><Bell size={28} className="mx-auto text-[var(--accent)]"/><p className="mt-3 font-black text-white">Sign in to see your notifications</p><div className="mt-4 flex gap-3"><a href="/auth?mode=signin" className="flex-1 rounded-xl bg-[var(--accent)] px-4 py-3 text-center text-sm font-bold text-white">Sign In</a><a href="/auth?mode=signup" className="flex-1 rounded-xl bg-[#0b3154] px-4 py-3 text-center text-sm font-bold text-white">Sign Up</a></div></div>:loading?<div className="surface-card mt-8 border-[var(--line)] p-8 text-center text-sm text-[var(--muted)]">Loading notifications…</div>:notifications.length===0?<div className="surface-card mt-8 text-center p-10"><Bell size={30} className="mx-auto text-[var(--accent)]"/><p className="mt-4 text-lg font-black text-white">You’re all caught up</p><p className="mt-1 text-sm text-[var(--muted)]">Your real MatchUp activity will appear here.</p></div>:<div className="mt-7 space-y-3">{notifications.map(item=>{const Icon=iconForKind(item.kind);const name=nameOf(item.actor);const unreadStyle=item.read_at?"border-[var(--line)] bg-[var(--panel)]":"border-[var(--accent)]/55 bg-[var(--accent-soft)]";return <button key={item.id} type="button" onClick={()=>void openNotification(item)} className={`group flex w-full items-center gap-3 rounded-2xl border p-3.5 text-left transition hover:border-[var(--accent)] ${unreadStyle}`}><div className="relative shrink-0">{item.actor?.avatar_path?<img src={item.actor.avatar_path} alt="" className="size-11 rounded-full object-cover"/>:<div className="grid size-11 place-items-center rounded-full bg-[#0b3154] text-sm font-black text-[var(--accent)]">{name.slice(0,1).toUpperCase()}</div>}<span className="absolute -bottom-0.5 -right-1 grid size-6 place-items-center rounded-full border-2 border-[#071426] bg-[var(--accent)] text-white"><Icon size={12}/></span></div><div className="min-w-0 flex-1"><p className={`text-sm leading-5 ${item.read_at?"font-semibold text-[#b7c9da]":"font-black text-white"}`}>{item.message}</p><div className="mt-1 flex items-center gap-2"><span className="text-[11px] font-semibold text-[var(--muted)]">{relativeTime(item.created_at)}</span>{!item.read_at?<span className="size-1.5 rounded-full bg-[var(--accent)]"/>:null}</div>{item.kind==="media_downloaded"&&item.postBody?<p className="mt-2 line-clamp-1 rounded-lg border border-[var(--line)] bg-black/15 px-2 py-1 text-[10px] text-[#b7c9da]">“{item.postBody}”</p>:null}</div>{item.thumbnail?<img src={item.thumbnail} alt="" className="size-12 shrink-0 rounded-xl object-cover"/>:<span className="text-xl text-[#4d759b]">›</span>}</button>;})}</div>}
 {error?<div className="fixed bottom-6 left-1/2 z-[140] flex max-w-[calc(100%-2rem)] -translate-x-1/2 items-center gap-3 rounded-2xl border border-[#234b70] bg-[#0a2139] px-4 py-3 text-xs font-bold text-white shadow-2xl"><span>{error}</span><button type="button" onClick={()=>setError("")} aria-label="Dismiss error"><X size={15}/></button></div>:null}
 {invite?<div className="fixed inset-0 z-[130] grid place-items-center bg-black/65 p-4" role="dialog" aria-modal="true"><div className="w-full max-w-sm overflow-hidden rounded-[28px] border border-[#194b7c] bg-[#071426] shadow-2xl"><div className="p-5 text-center">{invite.kind==="group"&&invite.group?<><div className="mx-auto grid size-20 place-items-center overflow-hidden rounded-3xl bg-[#0b3154] text-[var(--accent)]">{invite.group.image_path?<img src={invite.group.image_path} alt="" className="size-full object-cover"/>:<UsersRound size={30}/>}</div><h2 className="mt-4 text-xl font-black text-white">Join “{invite.group.name}”</h2><p className="mt-2 text-sm text-[#b7c9da]">Invited by <strong className="text-white">{nameOf(invite.inviter)}</strong></p><p className="mt-1 text-xs font-bold text-[var(--muted)]">{invite.group.member_count} {invite.group.member_count===1?"member":"members"}</p></>:null}{invite.kind==="tournament"&&invite.tournament?<><div className="mx-auto grid size-20 place-items-center rounded-3xl bg-[#0b3154] text-[var(--accent)]"><Trophy size={30}/></div><h2 className="mt-4 text-xl font-black text-white">{invite.tournament.name}</h2><p className="mt-2 text-sm text-[#b7c9da]">Invited by <strong className="text-white">{nameOf(invite.inviter)}</strong></p>{invite.tournament.game_title?<p className="mt-1 text-xs font-bold text-[var(--muted)]">{invite.tournament.game_title}</p>:null}{invite.tournament.starts_at?<p className="mt-1 text-xs text-[var(--muted)]">Starts {new Date(invite.tournament.starts_at).toLocaleString()}</p>:null}{invite.tournament.prize_pool!=null&&invite.tournament.prize_pool>0?<p className="mt-1 text-xs font-bold text-[var(--accent)]">Prize pool: {invite.tournament.prize_pool}</p>:null}{invite.tournament.description?<p className="mt-3 line-clamp-3 text-left text-sm leading-5 text-[#b7c9da]">{invite.tournament.description}</p>:null}</>:null}<div className="mt-6 grid grid-cols-2 gap-3"><button type="button" disabled={working} onClick={()=>void respond(true)} className="rounded-xl bg-[#167bd1] px-4 py-3.5 text-sm font-black text-white disabled:opacity-50"><Check size={16} className="mr-1 inline"/>Accept</button><button type="button" disabled={working} onClick={()=>void respond(false)} className="rounded-xl bg-[#173653] px-4 py-3.5 text-sm font-black text-white disabled:opacity-50"><X size={16} className="mr-1 inline"/>Decline</button></div><button type="button" disabled={working} onClick={()=>setInvite(null)} className="mt-3 w-full py-2 text-xs font-bold text-[#86a1bb]">Close</button></div></div></div>:null}
 </main>;
}
