"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, AtSign, Bell, CalendarDays, CheckCheck, FileText, Heart, Link2, MessageCircle, Trophy, UserPlus, UsersRound, UserRoundPlus, Zap } from "lucide-react";
import { useRouter } from "next/navigation";
import { createBrowserSupabaseClient } from "../../lib/supabase/client";

type NotificationRow={id:string;recipient_id:string;kind:string;payload:Record<string,unknown>|null;read_at:string|null;created_at:string};
type Profile={id:string;display_name:string|null;username:string|null;avatar_path:string|null};
type ViewNotification=NotificationRow&{actor?:Profile|null;message:string;href?:string|null;thumbnail?:string|null};
function iconForKind(kind:string){if(kind.includes("like"))return Heart;if(kind.includes("comment"))return MessageCircle;if(kind.includes("tag"))return AtSign;if(kind.includes("link"))return Link2;if(kind.startsWith("post"))return FileText;if(kind.startsWith("friend"))return UserPlus;if(kind.startsWith("group"))return UsersRound;if(kind.includes("boost"))return Zap;return Trophy;}
function payloadString(payload:Record<string,unknown>|null,key:string){const v=payload?.[key];return typeof v==="string"?v:null;}
function buildHref(row:NotificationRow){const explicit=payloadString(row.payload,"href");if(explicit)return explicit;const type=payloadString(row.payload,"entity_type");const id=payloadString(row.payload,"entity_id");if(!id)return null;if(type==="tournament")return `/tournaments/${id}`;if(type==="post")return `/feeds?post=${id}`;if(type==="profile")return `/leaderboard?add=friends&user=${id}`;if(type==="group")return `/leaderboard?group=${id}`;return null;}
function relativeTime(value:string){const minutes=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/60000));if(minutes<1)return "now";if(minutes<60)return `${minutes}m`;const hours=Math.floor(minutes/60);if(hours<24)return `${hours}h`;const days=Math.floor(hours/24);if(days<7)return `${days}d`;return new Date(value).toLocaleDateString();}
function dayGroup(value:string){const now=new Date();const date=new Date(value);const start=Date.UTC(now.getFullYear(),now.getMonth(),now.getDate());const target=Date.UTC(date.getFullYear(),date.getMonth(),date.getDate());const days=Math.floor((start-target)/86400000);if(days===0)return "Today";if(days===1)return "Yesterday";if(days<7)return "This Week";return "Earlier";}
export function NotificationsPage(){
 const router=useRouter();const supabase=useMemo(()=>createBrowserSupabaseClient(),[]);const [notifications,setNotifications]=useState<ViewNotification[]>([]);const [loading,setLoading]=useState(true);const [signedIn,setSignedIn]=useState(true);
 const load=useCallback(async()=>{setLoading(true);const {data:auth}=await supabase.auth.getUser();if(!auth.user){setSignedIn(false);setNotifications([]);setLoading(false);return;}setSignedIn(true);const {data,error}=await supabase.from("notifications").select("id,recipient_id,kind,payload,read_at,created_at").eq("recipient_id",auth.user.id).order("created_at",{ascending:false}).limit(200);if(error){setNotifications([]);setLoading(false);return;}const rows=(data||[]) as NotificationRow[];const actorIds=Array.from(new Set(rows.map(r=>payloadString(r.payload,"actor_id")).filter((id):id is string=>Boolean(id))));let profiles:Profile[]=[];if(actorIds.length){const {data:profileData}=await supabase.from("profiles").select("id,display_name,username,avatar_path").in("id",actorIds);profiles=(profileData||[]) as Profile[];}const map=new Map(profiles.map(p=>[p.id,p]));setNotifications(rows.map(row=>{const actorId=payloadString(row.payload,"actor_id");const actor=actorId?map.get(actorId)||null:null;return {...row,actor,message:payloadString(row.payload,"message")||row.kind.replaceAll("_"," "),href:buildHref(row),thumbnail:payloadString(row.payload,"thumbnail")};}));setLoading(false);},[supabase]);
 useEffect(()=>{void load();const channel=supabase.channel("user-notifications").on("postgres_changes",{event:"*",schema:"public",table:"notifications"},()=>void load()).subscribe();return()=>{void supabase.removeChannel(channel);};},[load,supabase]);
 const markRead=async(n:ViewNotification)=>{if(!n.read_at){const readAt=new Date().toISOString();const {error}=await supabase.from("notifications").update({read_at:readAt}).eq("id",n.id);if(!error)setNotifications(c=>c.map(x=>x.id===n.id?{...x,read_at:readAt}:x));}if(n.href)router.push(n.href);};
 const markAllRead=async()=>{const {data:auth}=await supabase.auth.getUser();if(!auth.user)return;const readAt=new Date().toISOString();const {error}=await supabase.from("notifications").update({read_at:readAt}).eq("recipient_id",auth.user.id).is("read_at",null);if(!error)setNotifications(c=>c.map(x=>({...x,read_at:x.read_at||readAt})));};
 const groups=["Today","Yesterday","This Week","Earlier"].map(label=>({label,items:notifications.filter(n=>dayGroup(n.created_at)===label)})).filter(g=>g.items.length);const unread=notifications.filter(n=>!n.read_at).length;
 return <main className="app-shell min-h-screen pb-28"><div className="flex items-center justify-between gap-4"><div className="flex items-center gap-3"><button type="button" onClick={()=>router.push("/home")} aria-label="Back to Home" className="icon-button"><ArrowLeft size={18}/></button><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#47a8ff]">MatchUp</p><h1 className="text-2xl font-black text-white">Notifications</h1></div></div>{unread>0?<button type="button" onClick={()=>void markAllRead()} className="flex items-center gap-2 rounded-xl border border-[#18365f] bg-[#0a1b2f] px-3 py-2 text-xs font-black text-[#c8d9e9]"><CheckCheck size={15}/>Mark all as read</button>:null}</div>
 {!signedIn?<div className="surface-card mt-8 border-[#153c68] p-8 text-center"><Bell size={28} className="mx-auto text-[#47a8ff]"/><p className="mt-3 font-black text-white">Sign in to see your notifications</p><div className="mt-4 flex gap-3"><a href="/auth/sign-in" className="flex-1 rounded-xl bg-[#167bd1] px-4 py-3 text-center text-sm font-bold text-white">Sign In</a><a href="/auth/sign-up" className="flex-1 rounded-xl border border-[#167bd1] px-4 py-3 text-center text-sm font-bold text-[#70c1ff]">Sign Up</a></div></div>:loading?<div className="surface-card mt-8 border-[#153c68] p-8 text-center text-sm text-[#7892ac]">Loading notifications…</div>:notifications.length===0?<div className="surface-card mt-8 border-[#153c68] p-10 text-center"><Bell size={30} className="mx-auto text-[#47a8ff]"/><p className="mt-4 text-lg font-black text-white">You're all caught up</p><p className="mt-1 text-sm text-[#7892ac]">Friend, group, post, tournament and activity notifications will appear here.</p></div>:<div className="mt-7 space-y-7">{groups.map(group=><section key={group.label}><div className="mb-3 flex items-center gap-2 text-[11px] font-black uppercase tracking-[.15em] text-[#66809a]"><CalendarDays size={13}/>{group.label}</div><div className="space-y-2">{group.items.map(item=>{const Icon=iconForKind(item.kind);const name=item.actor?.display_name||item.actor?.username||"MatchUp";return <button key={item.id} type="button" onClick={()=>void markRead(item)} className={`group flex w-full items-center gap-3 rounded-2xl border p-3 text-left transition hover:border-[#2497ff] ${item.read_at?"border-[#16324f] bg-[#071426]":"border-[#1e6095] bg-[#0a2139]"}`}><div className="relative shrink-0">{item.actor?.avatar_path?<img src={item.actor.avatar_path} alt="" className="size-11 rounded-full object-cover"/>:<div className="grid size-11 place-items-center rounded-full bg-[#0b3154] text-sm font-black text-[#70c1ff]">{name.slice(0,1).toUpperCase()}</div>}{!item.read_at?<span className="absolute -right-0.5 -top-0.5 size-3 rounded-full border-2 border-[#0a2139] bg-[#47a8ff]"/>:null}</div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><p className={`text-sm leading-5 ${item.read_at?"font-medium text-[#b7c9da]":"font-black text-white"}`}>{item.message}</p><span className="shrink-0 text-[10px] font-semibold text-[#66809a]">{relativeTime(item.created_at)}</span></div><div className="mt-1 flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-[.08em] text-[#66809a]"><Icon size={12}/>{item.kind.replaceAll("_"," ")}</div></div>{item.thumbnail?<img src={item.thumbnail} alt="" className="hidden size-12 shrink-0 rounded-xl object-cover sm:block"/>:null}</button>;})}</div></section>)}</div>}
 </main>;
}
