"use client";

import { useEffect, useMemo, useState } from "react";
import { CalendarDays, Plus, Search, Trophy, Users, Zap } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { createBrowserSupabaseClient } from "../../lib/supabase/client";

type Category = "boosted" | "featured" | "discover";
type TournamentRow = { id: string; tournament_id: string; name: string; description?: string | null; format: string; status: string; starts_at?: string | null; visibility: string; max_players: number; organizer_id: string; banner_path?: string | null; profiles?: { display_name?: string | null; username?: string | null } | Array<{ display_name?: string | null; username?: string | null }> | null; promotion_kind?: string | null; promotion_expires_at?: string | null };
const showcase = ["MatchUp Elite Finals", "Night League Championship", "Lagos Kings Cup", "Weekend Rivals", "Pro Division Clash", "Friday Night Showdown", "MatchUp Champions Cup", "Ultimate eFootball Arena", "Street to Stadium Cup", "Elite Masters League", "Next Gen Challenge", "Golden Boot Tournament", "Super Sunday Knockout", "National Rivalry Cup", "Legends Championship"];
function fallbackRows(category: Category): TournamentRow[] { return showcase.map((name, index) => ({ id: `demo-${category}-${index + 1}`, tournament_id: `DEMO-${category.toUpperCase()}-${index + 1}`, name, description: "Open MatchUp competition for competitive eFootball players.", format: ["knockout", "group_stage", "league"][index % 3], status: "open", starts_at: new Date(Date.now() + (index + 1) * 86400000).toISOString(), visibility: "public", max_players: [32, 64, 128][index % 3], organizer_id: "", banner_path: "/1002371685.jpg", promotion_kind: category === "boosted" ? "pin" : category === "featured" ? "featured" : null })); }
function normalizeRows(rows: TournamentRow[], category: Category) { const selected = rows.filter((row) => { const kind = row.promotion_kind; return category === "boosted" ? kind === "boost" || kind === "pin" : category === "featured" ? kind === "featured" || kind === "promoted" : !kind; }); const seen = new Set(selected.map((row) => row.id)); return [...selected, ...fallbackRows(category).filter((row) => !seen.has(row.id))].slice(0, 15); }
function profileName(row: TournamentRow) { const profile = Array.isArray(row.profiles) ? row.profiles[0] : row.profiles; return profile?.display_name || profile?.username || "MatchUp Organizer"; }
function formatName(value: string) { return value.replaceAll("_", " "); }

export function TournamentCard({ row, category }: { row: TournamentRow; category: Category }) {
  const router = useRouter(); const isDemo = row.id.startsWith("demo-"); const badge = category === "boosted" ? "Pinned" : category === "featured" ? "Featured" : null;
  return <button type="button" disabled={isDemo} onClick={() => router.push(`/tournaments/${row.id}`)} className={`group w-full overflow-hidden rounded-[20px] border border-[#2d2455] bg-[#0d0e20] text-left shadow-[0_14px_32px_rgba(40,15,90,.22)] transition hover:-translate-y-0.5 hover:border-[#7c4dff] ${isDemo ? "cursor-default" : "cursor-pointer"}`}>
    <div className="relative h-36 overflow-hidden bg-[#17142b]"><img src={row.banner_path || "/1002371685.jpg"} alt="" className="h-full w-full object-cover transition duration-300 group-hover:scale-[1.03]" /><div className="absolute inset-0 bg-gradient-to-t from-[#0d0e20] via-[#0d0e20]/20 to-[#0d0e20]/40" />{badge ? <span className={`absolute left-3 top-3 inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-[10px] font-black uppercase tracking-[.08em] ${category === "boosted" ? "border-[#7c4dff]/50 bg-[#2a1a55]/90 text-[#c8adff]" : "border-[#6d27ff]/40 bg-[#1f1640]/90 text-[#b79aff]"}`}><Zap size={11} />{badge}</span> : null}<span className="absolute bottom-3 left-3 rounded-full border border-[#7c4dff]/30 bg-[#1a1138]/80 px-2.5 py-1 text-[10px] font-bold uppercase tracking-[.08em] text-[#c8adff] backdrop-blur">{formatName(row.format)}</span></div>
    <div className="p-4"><div className="flex items-start justify-between gap-3"><h2 className="min-w-0 flex-1 truncate text-base font-black text-white">{row.name}</h2><Trophy size={16} className="mt-0.5 shrink-0 text-[#9a72ff]" /></div><p className="mt-1 line-clamp-1 text-xs text-[#89869b]">{row.description || "Open MatchUp competition."}</p><div className="mt-4 grid grid-cols-2 gap-2 text-[11px] text-[#bcb8cc]"><span className="flex items-center gap-1.5"><Users size={13} />{row.max_players} players</span><span className="flex items-center gap-1.5"><CalendarDays size={13} />{row.starts_at ? new Date(row.starts_at).toLocaleDateString() : "Date TBA"}</span></div><div className="mt-3 flex items-center justify-between border-t border-white/5 pt-3 text-[10px] font-semibold text-[#767388]"><span>{profileName(row)}</span><span className="capitalize">{formatName(row.status)}</span></div></div>
  </button>;
}

export function TournamentListingPage({ category, title }: { category: Category; title: string }) {
  const router = useRouter(); const supabase = useMemo(() => createBrowserSupabaseClient(), []); const [rows, setRows] = useState<TournamentRow[]>([]); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [idMode, setIdMode] = useState(false);
  useEffect(() => { const params = new URLSearchParams(window.location.search); setIdMode(params.get("mode") === "id"); }, []);
  useEffect(() => { let mounted = true; const load = async () => { const [tournamentsResult, promotionsResult] = await Promise.all([supabase.from("tournaments").select("id,tournament_id,name,description,format,status,starts_at,visibility,max_players,organizer_id,banner_path,profiles:organizer_id(display_name,username)").eq("visibility", "public").order("created_at", { ascending: false }), supabase.from("tournament_promotions").select("tournament_id,kind,expires_at,position").order("position", { ascending: true })]); if (!mounted) return; const promotions = promotionsResult.data || []; const enriched = (tournamentsResult.data || []).map((row: any) => { const active = promotions.find((promotion: any) => promotion.tournament_id === row.id && new Date(promotion.expires_at).getTime() > Date.now()); return { ...row, promotion_kind: active?.kind || null, promotion_expires_at: active?.expires_at || null } as TournamentRow; }); setRows(normalizeRows(enriched, category)); setLoading(false); }; void load(); return () => { mounted = false; }; }, [category, supabase]);
  const filtered = rows.filter((row) => !query.trim() || `${row.name} ${row.tournament_id} ${row.format} ${row.description || ""}`.toLowerCase().includes(query.trim().toLowerCase()));
  return <main className="app-shell pb-28"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#9a73ff]">MatchUp Tournaments</p><h1 className="mt-1 text-3xl font-black tracking-tight text-white">{title}</h1><p className="mt-1 max-w-xl text-sm leading-6 text-[#8f8ca1]">Browse this tournament category, find your next challenge, or build your own.</p></div><Link href="/tournaments/new" className="hidden shrink-0 items-center gap-2 rounded-2xl bg-[linear-gradient(100deg,#7026f5,#8e37ff)] px-4 py-3 text-xs font-black text-white sm:flex"><Plus size={15} />Create</Link></div><div className="mt-5 grid gap-3 sm:grid-cols-[1fr_auto]"><label className="flex items-center gap-2 rounded-2xl border border-[#28293f] bg-[#0d0e20] px-4 py-3"><Search size={17} className="text-[#737086]" /><input value={query} onChange={(event) => setQuery(event.target.value)} className="w-full bg-transparent text-sm text-white outline-none placeholder:text-[#666376]" placeholder={idMode ? "Paste tournament ID" : "Search tournaments"} aria-label={idMode ? "Paste tournament ID" : "Search tournaments"} /></label><div className="grid grid-cols-3 gap-2"><button type="button" onClick={() => document.getElementById("tournament-results")?.scrollIntoView({ behavior: "smooth" })} className="rounded-2xl border border-[#2b2b45] bg-[#121327] px-3 py-3 text-[11px] font-black text-white">Find Competition</button><button type="button" onClick={() => router.push("/tournaments/new")} className="rounded-2xl border border-[#2b2b45] bg-[#121327] px-3 py-3 text-[11px] font-black text-white">Build Your Own</button><button type="button" onClick={() => router.push("/tournaments/new")} className="rounded-2xl bg-[linear-gradient(100deg,#7026f5,#8e37ff)] px-3 py-3 text-[11px] font-black text-white">Create</button></div></div><div id="tournament-results" className="mt-7">{loading ? <div className="surface-card p-8 text-center text-sm text-[#89869b]">Loading tournaments…</div> : filtered.length ? <div className="grid gap-4 sm:grid-cols-2">{filtered.map((row) => <TournamentCard key={row.id} row={row} category={category} />)}</div> : <div className="surface-card p-8 text-center"><Search className="mx-auto text-[#7b48ec]" /><p className="mt-3 font-bold text-white">No tournaments found</p><p className="mt-1 text-sm text-[#77758b]">Try a different search.</p></div>}</div></main>;
}
