"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Check, MessageSquare, Search, UserPlus, UserRound, Users, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { createBrowserSupabaseClient } from "../../lib/supabase/client";
import { MatchUpAvatar, profileName, type MatchUpAvatarProfile } from "../matchup-avatar";

type Profile=MatchUpAvatarProfile&{username:string;display_name:string|null;avatar_path:string|null};type Relation={user_id:string;friend_id:string;status:string;created_at:string};type PrivateGroup={id:string;name:string;created_at:string};
export function FriendsPage(){
 const router=useRouter();const supabase=useMemo(()=>createBrowserSupabaseClient(),[]);const [userId,setUserId]=useState("");const [query,setQuery]=useState("");const [results,setResults]=useState<Profile[]>([]);const [friends,setFriends]=useState<Profile[]>([]);const [incoming,setIncoming]=useState<Array<Relation&{profile:Profile}>>([]);const [outgoing,setOutgoing]=useState<Relation[]>([]);const [conversations,setConversations]=useState<Array<{friend:Profile;group:PrivateGroup;preview:string;created_at:string}>>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState<string|null>(null);const [notice,setNotice]=useState<string|null>(null);const [accepted,setAccepted]=useState<Profile|null>(null);
 const load=useCallback(async()=>{setLoading(true);const {data:auth}=await supabase.auth.getUser();if(!auth.user){setUserId("");setLoading(false);return;}const uid=auth.user.id;setUserId(uid);const {data:relations}=await supabase.from("friendships").select("user_id,friend_id,status,created_at").or(`user_id.eq.${uid},friend_id.eq.${uid}`).order("created_at",{ascending:false}).limit(500);const rows=(relations||[]) as Relation[];const friendIds=rows.filter(r=>r.status==="accepted").map(r=>r.user_id===uid?r.friend_id:r.user_id);const incomingRows=rows.filter(r=>r.status==="pending"&&r.friend_id===uid);const outgoingRows=rows.filter(r=>r.status==="pending"&&r.user_id===uid);setOutgoing(outgoingRows);const ids=Array.from(new Set([...friendIds,incomingRows.map(r=>r.user_id),outgoingRows.map(r=>r.friend_id)].flat()));let map=new Map<string,Profile>();if(ids.length){const {data:ps}=await supabase.from("profiles").select("id,username,display_name,avatar_path").in("id",ids);map=new Map(((ps||[]) as Profile[]).map(p=>[p.id,p]));setFriends(friendIds.map(id=>map.get(id)).filter((p):p is Profile=>Boolean(p)));setIncoming(incomingRows.map(r=>({...r,profile:map.get(r.user_id)})).filter((r):r is Relation&{profile:Profile}=>Boolean(r.profile)));}else{setFriends([]);setIncoming([]);}
 const {data:pgs}=await supabase.from("chat_groups").select("id,name,created_at").eq("kind","private").order("created_at",{ascending:false}).limit(100);const privateGroups=(pgs||[]) as PrivateGroup[];if(privateGroups.length){const {data:members}=await supabase.from("chat_group_members").select("group_id,user_id").in("group_id",privateGroups.map(g=>g.id));const relevant=(members||[]).filter((m:any)=>privateGroups.some(g=>g.id===m.group_id));const conv=[] as Array<{friend:Profile;group:PrivateGroup;preview:string;created_at:string}>;for(const g of privateGroups){const memberIds=relevant.filter((m:any)=>m.group_id===g.id).map((m:any)=>m.user_id);const other=memberIds.find((id:string)=>id!==uid);const friend=other?map.get(other):undefined;if(friend)conv.push({friend,group:g,preview:"Private conversation",created_at:g.created_at});}setConversations(conv.slice(0,10));}else setConversations([]);setLoading(false);},[supabase]);
 useEffect(()=>{void load();const channel=supabase.channel("friends-realtime").on("postgres_changes",{event:"*",schema:"public",table:"friendships"},()=>void load()).subscribe();return()=>{void supabase.removeChannel(channel)}},[load,supabase]);
 useEffect(()=>{const q=query.trim();if(!q){setResults([]);return;}let cancelled=false;const run=async()=>{const {data}=await supabase.from("profiles").select("id,username,display_name,avatar_path").or(`username.ilike.%${q}%,display_name.ilike.%${q}%`).neq("id",userId).order("username").limit(25);if(!cancelled)setResults((data||[]) as Profile[])};void run();return()=>{cancelled=true}},[query,userId,supabase]);
 const relationFor=(id:string)=>friends.some(f=>f.id===id)?"friends":outgoing.some(r=>r.friend_id===id)?"pending":"none";const sendRequest=async(id:string)=>{setBusy(id);setNotice(null);const {error}=await supabase.rpc("send_friend_request",{p_target:id});if(error)setNotice(error.message.includes("Already friends")?"You are already friends.":"Could not send friend request.");else{setNotice("Friend request sent.");setQuery("");await load()}setBusy(null)};const cancelRequest=async(id:string)=>{setBusy(id);await supabase.from("friendships").delete().eq("user_id",userId).eq("friend_id",id).eq("status","pending");await load();setBusy(null)};const respond=async(sender:string,acceptRequest:boolean)=>{setBusy(sender);setNotice(null);const {error}=await supabase.rpc("respond_friend_request",{p_sender:sender,p_accept:acceptRequest});if(error)setNotice("Could not update the friend request.");else{const p=incoming.find(r=>r.user_id===sender)?.profile;if(acceptRequest&&p)setAccepted(p);setNotice(acceptRequest?"Friend request accepted.":"Friend request declined.");await load()}setBusy(null)};
 const message=(id:string)=>router.push(`/leaderboard?message=friends&friend=${id}`);
 return <main className="app-shell min-h-screen pb-28"><header className="mb-5"><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#47a8ff]">Connect</p><h1 className="mt-1 text-3xl font-black text-white">Messages</h1><div className="mt-5 grid grid-cols-2 rounded-2xl border border-[#18365f] bg-[#071426] p-1"><button type="button" className="rounded-xl bg-[#126bc0] px-4 py-3 text-xs font-black text-white shadow-lg" aria-current="page">FRIENDS</button><button type="button" onClick={()=>router.push("/groups")} className="rounded-xl px-4 py-3 text-xs font-black text-[#7892ac] hover:bg-[#0a2139]">GROUPS</button></div></header>
 {notice?<div role="status" className="mb-4 rounded-2xl border border-[#205d8e] bg-[#0a2946] px-4 py-3 text-sm font-bold text-[#bfe3ff]">{notice}</div>:null}
 <section><label className="flex items-center gap-3 rounded-2xl border border-[#18365f] bg-[#071426] px-4 py-3.5"><Search size={18} className="text-[#47a8ff]"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search MatchUp players" aria-label="Search friends" className="min-w-0 flex-1 bg-transparent text-sm text-white outline-none"/>{query?<button type="button" onClick={()=>setQuery("")} aria-label="Clear search"><X size={16}/></button>:null}</label>{results.length?<div className="mt-3 space-y-2">{results.map(p=>{const relation=relationFor(p.id);return <div key={p.id} className="flex items-center gap-3 rounded-2xl border border-[#18365f] bg-[#071426] p-3"><MatchUpAvatar profile={p} size={48}/><div className="min-w-0 flex-1"><p className="truncate font-black text-white">{profileName(p)}</p><p className="truncate text-xs text-[#7892ac]">@{p.username}</p></div>{relation==="friends"?<span className="text-xs font-bold text-[#7dc8ff]">Friends</span>:relation==="pending"?<button type="button" disabled={busy===p.id} onClick={()=>void cancelRequest(p.id)} className="rounded-xl border border-[#36506b] px-3 py-2 text-xs font-black text-[#b7c9da]">Cancel</button>:<button type="button" disabled={busy===p.id} onClick={()=>void sendRequest(p.id)} className="flex items-center gap-1.5 rounded-xl bg-[#167bd1] px-3 py-2 text-xs font-black text-white"><UserPlus size={14}/>{busy===p.id?"Sending…":"Add"}</button>}</div>})}</div>:query?<p className="py-8 text-center text-sm text-[#7892ac]">No MatchUp players found.</p>:null}</section>
 {incoming.length?<section className="mt-7"><h2 className="mb-3 text-lg font-black text-white">People who want to connect</h2><div className="space-y-2">{incoming.map(r=><div key={r.user_id} className="rounded-2xl border border-[#214a78] bg-[#0a2139] p-3"><div className="flex items-center gap-3"><MatchUpAvatar profile={r.profile} size={48}/><div className="min-w-0 flex-1"><p className="truncate font-black text-white">{profileName(r.profile)}</p><p className="text-xs text-[#7892ac]">@{r.profile.username}</p></div></div><div className="mt-3 grid grid-cols-2 gap-2"><button type="button" disabled={busy===r.user_id} onClick={()=>void respond(r.user_id,true)} className="rounded-xl bg-[#167bd1] px-4 py-2.5 text-xs font-black text-white"><Check size={14} className="mr-1 inline"/>Accept</button><button type="button" disabled={busy===r.user_id} onClick={()=>void respond(r.user_id,false)} className="rounded-xl border border-[#36506b] px-4 py-2.5 text-xs font-black text-[#b7c9da]"><X size={14} className="mr-1 inline"/>Decline</button></div></div>)}</div></section>:null}
 {conversations.length?<section className="mt-7"><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-black text-white">Recent conversations</h2><span className="text-xs font-bold text-[#7892ac]">{conversations.length}</span></div><div className="space-y-2">{conversations.map(c=><button key={c.group.id} type="button" onClick={()=>message(c.friend.id)} className="flex w-full items-center gap-3 rounded-2xl border border-[#18365f] bg-[#071426] p-3 text-left"><MatchUpAvatar profile={c.friend} size={50}/><span className="min-w-0 flex-1"><strong className="block truncate text-sm font-black text-white">{profileName(c.friend)}</strong><span className="mt-1 block truncate text-xs text-[#7892ac]">{c.preview}</span></span><MessageSquare size={18} className="text-[#47a8ff]"/></button>)}</div></section>:null}
 <section className="mt-7"><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-black text-white">Friends</h2><span className="text-xs font-bold text-[#7892ac]">{friends.length}</span></div>{loading?<div className="surface-card p-8 text-center text-sm text-[#7892ac]">Loading friends…</div>:friends.length?<div className="space-y-2">{friends.map(p=><div key={p.id} className="flex items-center gap-3 rounded-2xl border border-[#18365f] bg-[#071426] p-3"><MatchUpAvatar profile={p} size={50}/><div className="min-w-0 flex-1"><p className="truncate font-black text-white">{profileName(p)}</p><p className="truncate text-xs text-[#7892ac]">@{p.username}</p></div><button type="button" onClick={()=>message(p.id)} className="flex items-center gap-1.5 rounded-xl border border-[#216497] bg-[#0a2946] px-3 py-2 text-xs font-black text-[#9bd3ff]"><MessageSquare size={14}/>Message</button></div>)}</div>:<div className="surface-card p-8 text-center"><UserRound size={28} className="mx-auto text-[#47a8ff]"/><p className="mt-3 font-black text-white">No friends yet</p><p className="mt-1 text-sm text-[#7892ac]">Search a MatchUp username above to send your first request.</p></div>}</section>
 {accepted?<div className="fixed inset-0 z-[90] grid place-items-center bg-black/55 p-4" role="dialog" aria-modal="true"><div className="w-full max-w-sm rounded-3xl border border-[#194b7c] bg-[#08182b] p-5 text-center shadow-2xl"><div className="mx-auto grid size-14 place-items-center rounded-2xl bg-[#0b3154] text-[#70c1ff]"><Check size={26}/></div><h2 className="mt-4 text-xl font-black text-white">You’re now friends with {profileName(accepted)}</h2><p className="mt-2 text-sm text-[#7892ac]">Start a conversation now or keep browsing.</p><div className="mt-5 grid grid-cols-2 gap-2"><button type="button" onClick={()=>message(accepted.id||"")} className="rounded-xl bg-[#167bd1] px-4 py-3 text-xs font-black text-white">Message Now</button><button type="button" onClick={()=>setAccepted(null)} className="rounded-xl border border-[#36506b] px-4 py-3 text-xs font-black text-[#b7c9da]">Later</button></div></div></div>:null}
 </main>;
}
